package com.artclub.dao;

import com.artclub.model.ac_abstract;

public interface ac_abstractMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_abstract
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer acAbstractId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_abstract
     *
     * @mbggenerated
     */
    int insert(ac_abstract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_abstract
     *
     * @mbggenerated
     */
    int insertSelective(ac_abstract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_abstract
     *
     * @mbggenerated
     */
    ac_abstract selectByPrimaryKey(Integer acAbstractId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_abstract
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ac_abstract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_abstract
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ac_abstract record);
}