package com.artclub.dao;

import com.artclub.model.ac_course;

import java.util.List;
import java.util.Map;

public interface ac_courseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_course
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer acCourseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_course
     *
     * @mbggenerated
     */
    int insert(ac_course record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_course
     *
     * @mbggenerated
     */
    int insertSelective(ac_course record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_course
     *
     * @mbggenerated
     */
    ac_course selectByPrimaryKey(Integer acCourseId);



    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_course
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ac_course record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_course
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ac_course record);

    List<ac_course> selectByCourseName(String courseName);

    List<ac_course> selectByCourseNameLike(Map map);

    List<ac_course> selectByTeacherId(Integer teacherId);

    List<ac_course> selectAll();

    List<ac_course> selectAllFree();

    List<ac_course> selectAllFreeLimit(Map map);

    List<ac_course> selectAllPay();

    List<ac_course> selectAllPayLimit(Map map);

    List<ac_course> selcetByObjId(Integer objId);

    List<ac_course> selcetByObjIdLimit(Integer objId);

    ac_course selectByPrimaryKeyPay(Integer acCourseId);

    ac_course selectByPrimaryKeyFree(Integer acCourseId);

    List<ac_course> selectfourNew();

    List<ac_course> selectfourhot();

//    List<ac_course> selectAllBybestObj(Integer objId);

}