package com.artclub.dao;

import com.artclub.model.ac_company;

public interface ac_companyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_company
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer acCompanyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_company
     *
     * @mbggenerated
     */
    int insert(ac_company record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_company
     *
     * @mbggenerated
     */
    int insertSelective(ac_company record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_company
     *
     * @mbggenerated
     */
    ac_company selectByPrimaryKey(Integer acCompanyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_company
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ac_company record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_company
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ac_company record);
}