package com.artclub.dao;

import com.artclub.model.ac_course_instrument;

import java.util.List;
import java.util.Map;

public interface ac_course_instrumentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_course_instrument
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer acCourseInstrumentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_course_instrument
     *
     * @mbggenerated
     */
    int insert(ac_course_instrument record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_course_instrument
     *
     * @mbggenerated
     */
    int insertSelective(ac_course_instrument record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_course_instrument
     *
     * @mbggenerated
     */
    ac_course_instrument selectByPrimaryKey(Integer acCourseInstrumentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_course_instrument
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ac_course_instrument record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_course_instrument
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ac_course_instrument record);

    ac_course_instrument selectByInstrumentIdAndCourseId(Map map);

    List<ac_course_instrument> selectByInstrumentId(int instrumentId);

    List<ac_course_instrument> selectByCourseId(int courseId);
}