package com.artclub.dao;

import com.artclub.model.ac_course_object;

import java.util.List;
import java.util.Map;

public interface ac_course_objectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_course_object
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer acCourseObjectId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_course_object
     *
     * @mbggenerated
     */
    int insert(ac_course_object record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_course_object
     *
     * @mbggenerated
     */
    int insertSelective(ac_course_object record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_course_object
     *
     * @mbggenerated
     */
    ac_course_object selectByPrimaryKey(Integer acCourseObjectId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_course_object
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ac_course_object record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_course_object
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ac_course_object record);


    ac_course_object selectByObjectIdAndCourseId(Map map);

    List<ac_course_object> selectByObjectId(int instrumentId);

    List<ac_course_object> selectByCourseId(int courseId);
}