package com.artclub.dao;

import com.artclub.model.ac_course_video;

import java.util.List;
import java.util.Map;

public interface ac_course_videoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_course_video
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer acVideoCourseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_course_video
     *
     * @mbggenerated
     */
    int insert(ac_course_video record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_course_video
     *
     * @mbggenerated
     */
    int insertSelective(ac_course_video record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_course_video
     *
     * @mbggenerated
     */
    ac_course_video selectByPrimaryKey(Integer acVideoCourseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_course_video
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ac_course_video record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_course_video
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ac_course_video record);

    List<ac_course_video> selectByCourseId(int id);

    List<ac_course_video> selectChapterByCourseId(int id);

    List<ac_course_video> selectEpisodeByCourseIdAndChapterId(Map map);

    ac_course_video selectEpisodeByCourseIdAndChapterIdAndEpisode(Map map);
}