package com.artclub.dao;

import com.artclub.model.ac_dictionary;

public interface ac_dictionaryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_dictionary
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer acDictionaryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_dictionary
     *
     * @mbggenerated
     */
    int insert(ac_dictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_dictionary
     *
     * @mbggenerated
     */
    int insertSelective(ac_dictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_dictionary
     *
     * @mbggenerated
     */
    ac_dictionary selectByPrimaryKey(Integer acDictionaryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_dictionary
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ac_dictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_dictionary
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ac_dictionary record);
}