package com.artclub.dao;

import com.artclub.model.ac_instrument;

import java.util.List;

public interface ac_instrumentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_instrument
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer acInstrumentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_instrument
     *
     * @mbggenerated
     */
    int insert(ac_instrument record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_instrument
     *
     * @mbggenerated
     */
    int insertSelective(ac_instrument record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_instrument
     *
     * @mbggenerated
     */
    ac_instrument selectByPrimaryKey(Integer acInstrumentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_instrument
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ac_instrument record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_instrument
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ac_instrument record);

    //自己加的
    List<ac_instrument> selectAll();

    ac_instrument selectByIntrumentName(String instrumentName);
}