package com.artclub.dao;

import com.artclub.model.ac_message;

import java.util.List;
import java.util.Map;

public interface ac_messageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_message
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer acMessageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_message
     *
     * @mbggenerated
     */
    int insert(ac_message record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_message
     *
     * @mbggenerated
     */
    int insertSelective(ac_message record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_message
     *
     * @mbggenerated
     */
    ac_message selectByPrimaryKey(Integer acMessageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_message
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ac_message record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_message
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ac_message record);

    List<ac_message> selectAll();

    List<ac_message> selectLimit(Map map);


    List<ac_message> selectByAcOrderFTId(Map map);
}