package com.artclub.dao;

import com.artclub.model.ac_news;

import java.util.List;
import java.util.Map;

public interface ac_newsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_news
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer acNewsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_news
     *
     * @mbggenerated
     */
    int insert(ac_news record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_news
     *
     * @mbggenerated
     */
    int insertSelective(ac_news record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_news
     *
     * @mbggenerated
     */
    ac_news selectByPrimaryKey(Integer acNewsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_news
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ac_news record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_news
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ac_news record);


    List<ac_news> selectAll();

    List<ac_news> selectAllNews();

    List<ac_news> selectAllifm();

    List<ac_news> selectInPage(Map map);

    List<ac_news> selectInPageNews(Map map);

    List<ac_news> selectInPageifm(Map map);

    List<ac_news> selectByTitleLikely(Map title);

    List<ac_news> selectALLfour();

    List<ac_news> selectNewsfour();

    List<ac_news> selectifmfour();

    ac_news selectNewifm();
}