package com.artclub.dao;

import com.artclub.model.ac_outresume;

public interface ac_outresumeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_outresume
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer acOutresumeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_outresume
     *
     * @mbggenerated
     */
    int insert(ac_outresume record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_outresume
     *
     * @mbggenerated
     */
    int insertSelective(ac_outresume record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_outresume
     *
     * @mbggenerated
     */
    ac_outresume selectByPrimaryKey(Integer acOutresumeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_outresume
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ac_outresume record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_outresume
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ac_outresume record);
}