package com.artclub.dao;

import com.artclub.model.ac_order;

public interface ac_orderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_order
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer acOrderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_order
     *
     * @mbggenerated
     */
    int insert(ac_order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_order
     *
     * @mbggenerated
     */
    int insertSelective(ac_order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_order
     *
     * @mbggenerated
     */
    ac_order selectByPrimaryKey(Integer acOrderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ac_order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ac_order record);
}