package com.artclub.dao;

import com.artclub.model.ac_resume;

import java.util.List;

public interface ac_resumeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_resume
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer acResumeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_resume
     *
     * @mbggenerated
     */
    int insert(ac_resume record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_resume
     *
     * @mbggenerated
     */
    int insertSelective(ac_resume record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_resume
     *
     * @mbggenerated
     */
    ac_resume selectByPrimaryKey(Integer acResumeId);

    ac_resume selectByUserId(String acResumeRealid);

    List<ac_resume> selectByStatus(Integer acResumeStatus);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_resume
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ac_resume record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_resume
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ac_resume record);
}