package com.artclub.dao;

import com.artclub.model.ac_studentvideo;

import java.util.List;
import java.util.Map;

public interface ac_studentvideoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_studentvideo
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer acStudentvideoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_studentvideo
     *
     * @mbggenerated
     */
    int insert(ac_studentvideo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_studentvideo
     *
     * @mbggenerated
     */
    int insertSelective(ac_studentvideo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_studentvideo
     *
     * @mbggenerated
     */
    ac_studentvideo selectByPrimaryKey(Integer acStudentvideoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_studentvideo
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ac_studentvideo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_studentvideo
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ac_studentvideo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_studentvideo
     *
     * @mbggenerated
     */
    List<ac_studentvideo> selectStudnetVideoAuditing(Map map);

    List<ac_studentvideo> selectByValue(String value);

    List<ac_studentvideo> selcetAllAuditingVideo();
}