package com.artclub.dao;

import com.artclub.model.ac_student_course;

import java.util.List;
import java.util.Map;

public interface ac_student_courseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_student_course
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer acStudentCourseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_student_course
     *
     * @mbggenerated
     */
    int insert(ac_student_course record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_student_course
     *
     * @mbggenerated
     */
    int insertSelective(ac_student_course record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_student_course
     *
     * @mbggenerated
     */
    ac_student_course selectByPrimaryKey(Integer acStudentCourseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_student_course
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ac_student_course record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_student_course
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ac_student_course record);

    ac_student_course selectByStuIdAndCourseId(Map map);

    List<ac_student_course> selectByStuId(int stuId);

    List<ac_student_course> selectByCourseId(Integer acCourseId);
}