package com.artclub.dao;

import com.artclub.model.ac_teacher;
import com.artclub.model.ac_teacher_course;

import java.util.List;
import java.util.Map;

public interface ac_teacher_courseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_teacher_course
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer acTeacherCourseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_teacher_course
     *
     * @mbggenerated
     */
    int insert(ac_teacher_course record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_teacher_course
     *
     * @mbggenerated
     */
    int insertSelective(ac_teacher_course record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_teacher_course
     *
     * @mbggenerated
     */
    ac_teacher_course selectByPrimaryKey(Integer acTeacherCourseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_teacher_course
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ac_teacher_course record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_teacher_course
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ac_teacher_course record);

    ac_teacher_course selectByTidAndCid(Map map);

    List<ac_teacher_course> selectByTid(int tid);

    List<ac_teacher_course> selectByCid(int cid);

}