package com.artclub.dao;

import com.artclub.model.ac_teacher_instrument;

public interface ac_teacher_instrumentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_teacher_instrument
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer acTeacherInstrumentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_teacher_instrument
     *
     * @mbggenerated
     */
    int insert(ac_teacher_instrument record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_teacher_instrument
     *
     * @mbggenerated
     */
    int insertSelective(ac_teacher_instrument record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_teacher_instrument
     *
     * @mbggenerated
     */
    ac_teacher_instrument selectByPrimaryKey(Integer acTeacherInstrumentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_teacher_instrument
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ac_teacher_instrument record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_teacher_instrument
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ac_teacher_instrument record);
}