package com.artclub.dao;

import com.artclub.model.ac_teacher;

import java.util.List;
import java.util.Map;

public interface ac_teacherMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_teacher
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer acTeacherId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_teacher
     *
     * @mbggenerated
     */
    int insert(ac_teacher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_teacher
     *
     * @mbggenerated
     */
    int insertSelective(ac_teacher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_teacher
     *
     * @mbggenerated
     */
    ac_teacher selectByPrimaryKey(Integer acTeacherId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_teacher
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ac_teacher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_teacher
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ac_teacher record);


    List<ac_teacher> selectAll();

    ac_teacher selectByUserId(String userid);

    ac_teacher selectByCourseId(Integer teacherCourseId);

    List<ac_teacher> selectTeacherLikely(String message);

    List<ac_teacher> selectInPage(Map map);

    ac_teacher selectByNameAndRealId(ac_teacher ac_teacher);

    List<ac_teacher> selectAcTeacherByNameOrReadId(Map map);

    ac_teacher selectByUid(int id);


}