package com.artclub.dao;

import com.artclub.model.ac_user;

import java.util.List;
import java.util.Map;

public interface ac_userMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer acUserId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_user
     *
     * @mbggenerated
     */
    int insert(ac_user record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_user
     *
     * @mbggenerated
     */
    int insertSelective(ac_user record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_user
     *
     * @mbggenerated
     */
    ac_user selectByPrimaryKey(Integer acUserId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ac_user record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ac_user record);

    /**
     * �Լ��ӵ�
     */

    List<ac_user> selectAll();

    List<ac_user> selectInPage(Map map);

    ac_user selectByAccount(String account);

}