package com.artclub.dao;

import com.artclub.model.ac_video_assess;

import java.util.List;
import java.util.Map;

public interface ac_video_assessMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_video_assess
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer acVideoAssessId);

    int deleteByPrimaryKeys(Map acVideoAssessMessage);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_video_assess
     *
     * @mbggenerated
     */
    int insert(ac_video_assess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_video_assess
     *
     * @mbggenerated
     */
    int insertSelective(ac_video_assess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_video_assess
     *
     * @mbggenerated
     */
    ac_video_assess selectByPrimaryKey(Integer acVideoAssessId);

    ac_video_assess selectByPrimaryKeys(Map acVideoAssessMessage);

    List<ac_video_assess> selectAllByKeys(Map acVideoAssessMessage);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_video_assess
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ac_video_assess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_video_assess
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ac_video_assess record);
}