package com.artclub.model;

import java.io.Serializable;

public class ac_abstract implements Serializable {


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_abstract.ac_abstract_id
     *
     * @mbggenerated
     */
    private Integer acAbstractId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_abstract.ac_abstract_context
     *
     * @mbggenerated
     */
    private String acAbstractContext;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_abstract.ac_abstract_time
     *
     * @mbggenerated
     */
    private String acAbstractTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ac_abstract
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_abstract.ac_abstract_id
     *
     * @return the value of ac_abstract.ac_abstract_id
     *
     * @mbggenerated
     */
    public Integer getAcAbstractId() {
        return acAbstractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_abstract.ac_abstract_id
     *
     * @param acAbstractId the value for ac_abstract.ac_abstract_id
     *
     * @mbggenerated
     */
    public void setAcAbstractId(Integer acAbstractId) {
        this.acAbstractId = acAbstractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_abstract.ac_abstract_context
     *
     * @return the value of ac_abstract.ac_abstract_context
     *
     * @mbggenerated
     */
    public String getAcAbstractContext() {
        return acAbstractContext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_abstract.ac_abstract_context
     *
     * @param acAbstractContext the value for ac_abstract.ac_abstract_context
     *
     * @mbggenerated
     */
    public void setAcAbstractContext(String acAbstractContext) {
        this.acAbstractContext = acAbstractContext == null ? null : acAbstractContext.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_abstract.ac_abstract_time
     *
     * @return the value of ac_abstract.ac_abstract_time
     *
     * @mbggenerated
     */
    public String getAcAbstractTime() {
        return acAbstractTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_abstract.ac_abstract_time
     *
     * @param acAbstractTime the value for ac_abstract.ac_abstract_time
     *
     * @mbggenerated
     */
    public void setAcAbstractTime(String acAbstractTime) {
        this.acAbstractTime = acAbstractTime == null ? null : acAbstractTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_abstract
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ac_abstract other = (ac_abstract) that;
        return (this.getAcAbstractId() == null ? other.getAcAbstractId() == null : this.getAcAbstractId().equals(other.getAcAbstractId()))
            && (this.getAcAbstractContext() == null ? other.getAcAbstractContext() == null : this.getAcAbstractContext().equals(other.getAcAbstractContext()))
            && (this.getAcAbstractTime() == null ? other.getAcAbstractTime() == null : this.getAcAbstractTime().equals(other.getAcAbstractTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_abstract
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getAcAbstractId() == null) ? 0 : getAcAbstractId().hashCode());
        result = prime * result + ((getAcAbstractContext() == null) ? 0 : getAcAbstractContext().hashCode());
        result = prime * result + ((getAcAbstractTime() == null) ? 0 : getAcAbstractTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_abstract
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", acAbstractId=").append(acAbstractId);
        sb.append(", acAbstractContext=").append(acAbstractContext);
        sb.append(", acAbstractTime=").append(acAbstractTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}