package com.artclub.model;

import java.io.Serializable;

public class ac_course_instrument implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_course_instrument.ac_course_instrument_id
     *
     * @mbggenerated
     */
    private Integer acCourseInstrumentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_course_instrument.ac_course_instrument_courseid
     *
     * @mbggenerated
     */
    private Integer acCourseInstrumentCourseid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_course_instrument.ac_course_instrument_instrumentId
     *
     * @mbggenerated
     */
    private Integer acCourseInstrumentInstrumentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_course_instrument.ac_course_instrument_addtime
     *
     * @mbggenerated
     */
    private String acCourseInstrumentAddtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ac_course_instrument
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_course_instrument.ac_course_instrument_id
     *
     * @return the value of ac_course_instrument.ac_course_instrument_id
     *
     * @mbggenerated
     */
    public Integer getAcCourseInstrumentId() {
        return acCourseInstrumentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_course_instrument.ac_course_instrument_id
     *
     * @param acCourseInstrumentId the value for ac_course_instrument.ac_course_instrument_id
     *
     * @mbggenerated
     */
    public void setAcCourseInstrumentId(Integer acCourseInstrumentId) {
        this.acCourseInstrumentId = acCourseInstrumentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_course_instrument.ac_course_instrument_courseid
     *
     * @return the value of ac_course_instrument.ac_course_instrument_courseid
     *
     * @mbggenerated
     */
    public Integer getAcCourseInstrumentCourseid() {
        return acCourseInstrumentCourseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_course_instrument.ac_course_instrument_courseid
     *
     * @param acCourseInstrumentCourseid the value for ac_course_instrument.ac_course_instrument_courseid
     *
     * @mbggenerated
     */
    public void setAcCourseInstrumentCourseid(Integer acCourseInstrumentCourseid) {
        this.acCourseInstrumentCourseid = acCourseInstrumentCourseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_course_instrument.ac_course_instrument_instrumentId
     *
     * @return the value of ac_course_instrument.ac_course_instrument_instrumentId
     *
     * @mbggenerated
     */
    public Integer getAcCourseInstrumentInstrumentid() {
        return acCourseInstrumentInstrumentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_course_instrument.ac_course_instrument_instrumentId
     *
     * @param acCourseInstrumentInstrumentid the value for ac_course_instrument.ac_course_instrument_instrumentId
     *
     * @mbggenerated
     */
    public void setAcCourseInstrumentInstrumentid(Integer acCourseInstrumentInstrumentid) {
        this.acCourseInstrumentInstrumentid = acCourseInstrumentInstrumentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_course_instrument.ac_course_instrument_addtime
     *
     * @return the value of ac_course_instrument.ac_course_instrument_addtime
     *
     * @mbggenerated
     */
    public String getAcCourseInstrumentAddtime() {
        return acCourseInstrumentAddtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_course_instrument.ac_course_instrument_addtime
     *
     * @param acCourseInstrumentAddtime the value for ac_course_instrument.ac_course_instrument_addtime
     *
     * @mbggenerated
     */
    public void setAcCourseInstrumentAddtime(String acCourseInstrumentAddtime) {
        this.acCourseInstrumentAddtime = acCourseInstrumentAddtime == null ? null : acCourseInstrumentAddtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_course_instrument
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ac_course_instrument other = (ac_course_instrument) that;
        return (this.getAcCourseInstrumentId() == null ? other.getAcCourseInstrumentId() == null : this.getAcCourseInstrumentId().equals(other.getAcCourseInstrumentId()))
            && (this.getAcCourseInstrumentCourseid() == null ? other.getAcCourseInstrumentCourseid() == null : this.getAcCourseInstrumentCourseid().equals(other.getAcCourseInstrumentCourseid()))
            && (this.getAcCourseInstrumentInstrumentid() == null ? other.getAcCourseInstrumentInstrumentid() == null : this.getAcCourseInstrumentInstrumentid().equals(other.getAcCourseInstrumentInstrumentid()))
            && (this.getAcCourseInstrumentAddtime() == null ? other.getAcCourseInstrumentAddtime() == null : this.getAcCourseInstrumentAddtime().equals(other.getAcCourseInstrumentAddtime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_course_instrument
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getAcCourseInstrumentId() == null) ? 0 : getAcCourseInstrumentId().hashCode());
        result = prime * result + ((getAcCourseInstrumentCourseid() == null) ? 0 : getAcCourseInstrumentCourseid().hashCode());
        result = prime * result + ((getAcCourseInstrumentInstrumentid() == null) ? 0 : getAcCourseInstrumentInstrumentid().hashCode());
        result = prime * result + ((getAcCourseInstrumentAddtime() == null) ? 0 : getAcCourseInstrumentAddtime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_course_instrument
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", acCourseInstrumentId=").append(acCourseInstrumentId);
        sb.append(", acCourseInstrumentCourseid=").append(acCourseInstrumentCourseid);
        sb.append(", acCourseInstrumentInstrumentid=").append(acCourseInstrumentInstrumentid);
        sb.append(", acCourseInstrumentAddtime=").append(acCourseInstrumentAddtime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}