package com.artclub.model;

import java.io.Serializable;

public class ac_comments implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_comments.ac_comments_id
     *
     * @mbggenerated
     */
    private Integer acCommentsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_comments.ac_comments_parent
     *
     * @mbggenerated
     */
    private Integer acCommentsParent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_comments.ac_comments_from
     *
     * @mbggenerated
     */
    private Integer acCommentsFrom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_comments.ac_comments_to
     *
     * @mbggenerated
     */
    private Integer acCommentsTo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_comments.ac_comments_level
     *
     * @mbggenerated
     */
    private Integer acCommentsLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_comments.ac_comments_message
     *
     * @mbggenerated
     */
    private String acCommentsMessage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_comments.ac_comments_addtime
     *
     * @mbggenerated
     */
    private String acCommentsAddtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_comments.ac_comments_status
     *
     * @mbggenerated
     */
    private Integer acCommentsStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_comments.ac_comments_fromTable
     *
     * @mbggenerated
     */
    private String acCommentsFromtable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_comments.ac_comments_seneitive
     *
     * @mbggenerated
     */
    private String acCommentsSeneitive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ac_comments
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_comments.ac_comments_id
     *
     * @return the value of ac_comments.ac_comments_id
     *
     * @mbggenerated
     */
    public Integer getAcCommentsId() {
        return acCommentsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_comments.ac_comments_id
     *
     * @param acCommentsId the value for ac_comments.ac_comments_id
     *
     * @mbggenerated
     */
    public void setAcCommentsId(Integer acCommentsId) {
        this.acCommentsId = acCommentsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_comments.ac_comments_parent
     *
     * @return the value of ac_comments.ac_comments_parent
     *
     * @mbggenerated
     */
    public Integer getAcCommentsParent() {
        return acCommentsParent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_comments.ac_comments_parent
     *
     * @param acCommentsParent the value for ac_comments.ac_comments_parent
     *
     * @mbggenerated
     */
    public void setAcCommentsParent(Integer acCommentsParent) {
        this.acCommentsParent = acCommentsParent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_comments.ac_comments_from
     *
     * @return the value of ac_comments.ac_comments_from
     *
     * @mbggenerated
     */
    public Integer getAcCommentsFrom() {
        return acCommentsFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_comments.ac_comments_from
     *
     * @param acCommentsFrom the value for ac_comments.ac_comments_from
     *
     * @mbggenerated
     */
    public void setAcCommentsFrom(Integer acCommentsFrom) {
        this.acCommentsFrom = acCommentsFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_comments.ac_comments_to
     *
     * @return the value of ac_comments.ac_comments_to
     *
     * @mbggenerated
     */
    public Integer getAcCommentsTo() {
        return acCommentsTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_comments.ac_comments_to
     *
     * @param acCommentsTo the value for ac_comments.ac_comments_to
     *
     * @mbggenerated
     */
    public void setAcCommentsTo(Integer acCommentsTo) {
        this.acCommentsTo = acCommentsTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_comments.ac_comments_level
     *
     * @return the value of ac_comments.ac_comments_level
     *
     * @mbggenerated
     */
    public Integer getAcCommentsLevel() {
        return acCommentsLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_comments.ac_comments_level
     *
     * @param acCommentsLevel the value for ac_comments.ac_comments_level
     *
     * @mbggenerated
     */
    public void setAcCommentsLevel(Integer acCommentsLevel) {
        this.acCommentsLevel = acCommentsLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_comments.ac_comments_message
     *
     * @return the value of ac_comments.ac_comments_message
     *
     * @mbggenerated
     */
    public String getAcCommentsMessage() {
        return acCommentsMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_comments.ac_comments_message
     *
     * @param acCommentsMessage the value for ac_comments.ac_comments_message
     *
     * @mbggenerated
     */
    public void setAcCommentsMessage(String acCommentsMessage) {
        this.acCommentsMessage = acCommentsMessage == null ? null : acCommentsMessage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_comments.ac_comments_addtime
     *
     * @return the value of ac_comments.ac_comments_addtime
     *
     * @mbggenerated
     */
    public String getAcCommentsAddtime() {
        return acCommentsAddtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_comments.ac_comments_addtime
     *
     * @param acCommentsAddtime the value for ac_comments.ac_comments_addtime
     *
     * @mbggenerated
     */
    public void setAcCommentsAddtime(String acCommentsAddtime) {
        this.acCommentsAddtime = acCommentsAddtime == null ? null : acCommentsAddtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_comments.ac_comments_status
     *
     * @return the value of ac_comments.ac_comments_status
     *
     * @mbggenerated
     */
    public Integer getAcCommentsStatus() {
        return acCommentsStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_comments.ac_comments_status
     *
     * @param acCommentsStatus the value for ac_comments.ac_comments_status
     *
     * @mbggenerated
     */
    public void setAcCommentsStatus(Integer acCommentsStatus) {
        this.acCommentsStatus = acCommentsStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_comments.ac_comments_fromTable
     *
     * @return the value of ac_comments.ac_comments_fromTable
     *
     * @mbggenerated
     */
    public String getAcCommentsFromtable() {
        return acCommentsFromtable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_comments.ac_comments_fromTable
     *
     * @param acCommentsFromtable the value for ac_comments.ac_comments_fromTable
     *
     * @mbggenerated
     */
    public void setAcCommentsFromtable(String acCommentsFromtable) {
        this.acCommentsFromtable = acCommentsFromtable == null ? null : acCommentsFromtable.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_comments.ac_comments_seneitive
     *
     * @return the value of ac_comments.ac_comments_seneitive
     *
     * @mbggenerated
     */
    public String getAcCommentsSeneitive() {
        return acCommentsSeneitive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_comments.ac_comments_seneitive
     *
     * @param acCommentsSeneitive the value for ac_comments.ac_comments_seneitive
     *
     * @mbggenerated
     */
    public void setAcCommentsSeneitive(String acCommentsSeneitive) {
        this.acCommentsSeneitive = acCommentsSeneitive == null ? null : acCommentsSeneitive.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_comments
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ac_comments other = (ac_comments) that;
        return (this.getAcCommentsId() == null ? other.getAcCommentsId() == null : this.getAcCommentsId().equals(other.getAcCommentsId()))
            && (this.getAcCommentsParent() == null ? other.getAcCommentsParent() == null : this.getAcCommentsParent().equals(other.getAcCommentsParent()))
            && (this.getAcCommentsFrom() == null ? other.getAcCommentsFrom() == null : this.getAcCommentsFrom().equals(other.getAcCommentsFrom()))
            && (this.getAcCommentsTo() == null ? other.getAcCommentsTo() == null : this.getAcCommentsTo().equals(other.getAcCommentsTo()))
            && (this.getAcCommentsLevel() == null ? other.getAcCommentsLevel() == null : this.getAcCommentsLevel().equals(other.getAcCommentsLevel()))
            && (this.getAcCommentsMessage() == null ? other.getAcCommentsMessage() == null : this.getAcCommentsMessage().equals(other.getAcCommentsMessage()))
            && (this.getAcCommentsAddtime() == null ? other.getAcCommentsAddtime() == null : this.getAcCommentsAddtime().equals(other.getAcCommentsAddtime()))
            && (this.getAcCommentsStatus() == null ? other.getAcCommentsStatus() == null : this.getAcCommentsStatus().equals(other.getAcCommentsStatus()))
            && (this.getAcCommentsFromtable() == null ? other.getAcCommentsFromtable() == null : this.getAcCommentsFromtable().equals(other.getAcCommentsFromtable()))
            && (this.getAcCommentsSeneitive() == null ? other.getAcCommentsSeneitive() == null : this.getAcCommentsSeneitive().equals(other.getAcCommentsSeneitive()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_comments
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getAcCommentsId() == null) ? 0 : getAcCommentsId().hashCode());
        result = prime * result + ((getAcCommentsParent() == null) ? 0 : getAcCommentsParent().hashCode());
        result = prime * result + ((getAcCommentsFrom() == null) ? 0 : getAcCommentsFrom().hashCode());
        result = prime * result + ((getAcCommentsTo() == null) ? 0 : getAcCommentsTo().hashCode());
        result = prime * result + ((getAcCommentsLevel() == null) ? 0 : getAcCommentsLevel().hashCode());
        result = prime * result + ((getAcCommentsMessage() == null) ? 0 : getAcCommentsMessage().hashCode());
        result = prime * result + ((getAcCommentsAddtime() == null) ? 0 : getAcCommentsAddtime().hashCode());
        result = prime * result + ((getAcCommentsStatus() == null) ? 0 : getAcCommentsStatus().hashCode());
        result = prime * result + ((getAcCommentsFromtable() == null) ? 0 : getAcCommentsFromtable().hashCode());
        result = prime * result + ((getAcCommentsSeneitive() == null) ? 0 : getAcCommentsSeneitive().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_comments
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", acCommentsId=").append(acCommentsId);
        sb.append(", acCommentsParent=").append(acCommentsParent);
        sb.append(", acCommentsFrom=").append(acCommentsFrom);
        sb.append(", acCommentsTo=").append(acCommentsTo);
        sb.append(", acCommentsLevel=").append(acCommentsLevel);
        sb.append(", acCommentsMessage=").append(acCommentsMessage);
        sb.append(", acCommentsAddtime=").append(acCommentsAddtime);
        sb.append(", acCommentsStatus=").append(acCommentsStatus);
        sb.append(", acCommentsFromtable=").append(acCommentsFromtable);
        sb.append(", acCommentsSeneitive=").append(acCommentsSeneitive);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}