package com.artclub.model;

import java.io.Serializable;

public class ac_course implements Serializable {
    public String getTeacherName() {
        return teacherName;
    }

    public void setTeacherName(String teacherName) {
        this.teacherName = teacherName;
    }

    private String lv1Name;

    private String lv2Name;

    private String teacherName;

    public String getLv1Name() {
        return lv1Name;
    }

    public void setLv1Name(String lv1Name) {
        this.lv1Name = lv1Name;
    }

    public String getLv2Name() {
        return lv2Name;
    }

    public void setLv2Name(String lv2Name) {
        this.lv2Name = lv2Name;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_course.ac_course_id
     *
     * @mbggenerated
     */
    private Integer acCourseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_course.ac_course_name
     *
     * @mbggenerated
     */
    private String acCourseName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_course.ac_course_num
     *
     * @mbggenerated
     */
    private String acCourseNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_course.ac_course_time
     *
     * @mbggenerated
     */
    private String acCourseTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_course.ac_course_money
     *
     * @mbggenerated
     */
    private String acCourseMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_course.ac_course_status
     *
     * @mbggenerated
     */
    private String acCourseStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_course.ac_course_place
     *
     * @mbggenerated
     */
    private String acCoursePlace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_course.ac_course_pickNum
     *
     * @mbggenerated
     */
    private Integer acCoursePicknum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_course.ac_course_context
     *
     * @mbggenerated
     */
    private String acCourseContext;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_course.ac_course_img
     *
     * @mbggenerated
     */
    private String acCourseImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ac_course
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_course.ac_course_id
     *
     * @return the value of ac_course.ac_course_id
     * @mbggenerated
     */
    public Integer getAcCourseId() {
        return acCourseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_course.ac_course_id
     *
     * @param acCourseId the value for ac_course.ac_course_id
     * @mbggenerated
     */
    public void setAcCourseId(Integer acCourseId) {
        this.acCourseId = acCourseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_course.ac_course_name
     *
     * @return the value of ac_course.ac_course_name
     * @mbggenerated
     */
    public String getAcCourseName() {
        return acCourseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_course.ac_course_name
     *
     * @param acCourseName the value for ac_course.ac_course_name
     * @mbggenerated
     */
    public void setAcCourseName(String acCourseName) {
        this.acCourseName = acCourseName == null ? null : acCourseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_course.ac_course_num
     *
     * @return the value of ac_course.ac_course_num
     * @mbggenerated
     */
    public String getAcCourseNum() {
        return acCourseNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_course.ac_course_num
     *
     * @param acCourseNum the value for ac_course.ac_course_num
     * @mbggenerated
     */
    public void setAcCourseNum(String acCourseNum) {
        this.acCourseNum = acCourseNum == null ? null : acCourseNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_course.ac_course_time
     *
     * @return the value of ac_course.ac_course_time
     * @mbggenerated
     */
    public String getAcCourseTime() {
        return acCourseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_course.ac_course_time
     *
     * @param acCourseTime the value for ac_course.ac_course_time
     * @mbggenerated
     */
    public void setAcCourseTime(String acCourseTime) {
        this.acCourseTime = acCourseTime == null ? null : acCourseTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_course.ac_course_money
     *
     * @return the value of ac_course.ac_course_money
     * @mbggenerated
     */
    public String getAcCourseMoney() {
        return acCourseMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_course.ac_course_money
     *
     * @param acCourseMoney the value for ac_course.ac_course_money
     * @mbggenerated
     */
    public void setAcCourseMoney(String acCourseMoney) {
        this.acCourseMoney = acCourseMoney == null ? null : acCourseMoney.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_course.ac_course_status
     *
     * @return the value of ac_course.ac_course_status
     * @mbggenerated
     */
    public String getAcCourseStatus() {
        return acCourseStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_course.ac_course_status
     *
     * @param acCourseStatus the value for ac_course.ac_course_status
     * @mbggenerated
     */
    public void setAcCourseStatus(String acCourseStatus) {
        this.acCourseStatus = acCourseStatus == null ? null : acCourseStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_course.ac_course_place
     *
     * @return the value of ac_course.ac_course_place
     * @mbggenerated
     */
    public String getAcCoursePlace() {
        return acCoursePlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_course.ac_course_place
     *
     * @param acCoursePlace the value for ac_course.ac_course_place
     * @mbggenerated
     */
    public void setAcCoursePlace(String acCoursePlace) {
        this.acCoursePlace = acCoursePlace == null ? null : acCoursePlace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_course.ac_course_pickNum
     *
     * @return the value of ac_course.ac_course_pickNum
     * @mbggenerated
     */
    public Integer getAcCoursePicknum() {
        return acCoursePicknum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_course.ac_course_pickNum
     *
     * @param acCoursePicknum the value for ac_course.ac_course_pickNum
     * @mbggenerated
     */
    public void setAcCoursePicknum(Integer acCoursePicknum) {
        this.acCoursePicknum = acCoursePicknum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_course.ac_course_context
     *
     * @return the value of ac_course.ac_course_context
     * @mbggenerated
     */
    public String getAcCourseContext() {
        return acCourseContext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_course.ac_course_context
     *
     * @param acCourseContext the value for ac_course.ac_course_context
     * @mbggenerated
     */
    public void setAcCourseContext(String acCourseContext) {
        this.acCourseContext = acCourseContext == null ? null : acCourseContext.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_course.ac_course_img
     *
     * @return the value of ac_course.ac_course_img
     * @mbggenerated
     */
    public String getAcCourseImg() {
        return acCourseImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_course.ac_course_img
     *
     * @param acCourseImg the value for ac_course.ac_course_img
     * @mbggenerated
     */
    public void setAcCourseImg(String acCourseImg) {
        this.acCourseImg = acCourseImg == null ? null : acCourseImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_course
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ac_course other = (ac_course) that;
        return (this.getAcCourseId() == null ? other.getAcCourseId() == null : this.getAcCourseId().equals(other.getAcCourseId())) && (this.getAcCourseName() == null ? other.getAcCourseName() == null : this.getAcCourseName().equals(other.getAcCourseName())) && (this.getAcCourseNum() == null ? other.getAcCourseNum() == null : this.getAcCourseNum().equals(other.getAcCourseNum())) && (this.getAcCourseTime() == null ? other.getAcCourseTime() == null : this.getAcCourseTime().equals(other.getAcCourseTime())) && (this.getAcCourseMoney() == null ? other.getAcCourseMoney() == null : this.getAcCourseMoney().equals(other.getAcCourseMoney())) && (this.getAcCourseStatus() == null ? other.getAcCourseStatus() == null : this.getAcCourseStatus().equals(other.getAcCourseStatus())) && (this.getAcCoursePlace() == null ? other.getAcCoursePlace() == null : this.getAcCoursePlace().equals(other.getAcCoursePlace())) && (this.getAcCoursePicknum() == null ? other.getAcCoursePicknum() == null : this.getAcCoursePicknum().equals(other.getAcCoursePicknum())) && (this.getAcCourseContext() == null ? other.getAcCourseContext() == null : this.getAcCourseContext().equals(other.getAcCourseContext())) && (this.getAcCourseImg() == null ? other.getAcCourseImg() == null : this.getAcCourseImg().equals(other.getAcCourseImg()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_course
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getAcCourseId() == null) ? 0 : getAcCourseId().hashCode());
        result = prime * result + ((getAcCourseName() == null) ? 0 : getAcCourseName().hashCode());
        result = prime * result + ((getAcCourseNum() == null) ? 0 : getAcCourseNum().hashCode());
        result = prime * result + ((getAcCourseTime() == null) ? 0 : getAcCourseTime().hashCode());
        result = prime * result + ((getAcCourseMoney() == null) ? 0 : getAcCourseMoney().hashCode());
        result = prime * result + ((getAcCourseStatus() == null) ? 0 : getAcCourseStatus().hashCode());
        result = prime * result + ((getAcCoursePlace() == null) ? 0 : getAcCoursePlace().hashCode());
        result = prime * result + ((getAcCoursePicknum() == null) ? 0 : getAcCoursePicknum().hashCode());
        result = prime * result + ((getAcCourseContext() == null) ? 0 : getAcCourseContext().hashCode());
        result = prime * result + ((getAcCourseImg() == null) ? 0 : getAcCourseImg().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_course
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", acCourseId=").append(acCourseId);
        sb.append(", acCourseName=").append(acCourseName);
        sb.append(", acCourseNum=").append(acCourseNum);
        sb.append(", acCourseTime=").append(acCourseTime);
        sb.append(", acCourseMoney=").append(acCourseMoney);
        sb.append(", acCourseStatus=").append(acCourseStatus);
        sb.append(", acCoursePlace=").append(acCoursePlace);
        sb.append(", acCoursePicknum=").append(acCoursePicknum);
        sb.append(", acCourseContext=").append(acCourseContext);
        sb.append(", acCourseImg=").append(acCourseImg);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}