package com.artclub.model;

import java.io.Serializable;

public class ac_company implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_company.ac_company_id
     *
     * @mbggenerated
     */
    private Integer acCompanyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_company.ac_company_name
     *
     * @mbggenerated
     */
    private String acCompanyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_company.ac_company_url
     *
     * @mbggenerated
     */
    private String acCompanyUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_company.ac_company_logo
     *
     * @mbggenerated
     */
    private String acCompanyLogo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_company.ac_company_type
     *
     * @mbggenerated
     */
    private String acCompanyType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_company.ac_company_context
     *
     * @mbggenerated
     */
    private String acCompanyContext;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ac_company
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_company.ac_company_id
     *
     * @return the value of ac_company.ac_company_id
     *
     * @mbggenerated
     */
    public Integer getAcCompanyId() {
        return acCompanyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_company.ac_company_id
     *
     * @param acCompanyId the value for ac_company.ac_company_id
     *
     * @mbggenerated
     */
    public void setAcCompanyId(Integer acCompanyId) {
        this.acCompanyId = acCompanyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_company.ac_company_name
     *
     * @return the value of ac_company.ac_company_name
     *
     * @mbggenerated
     */
    public String getAcCompanyName() {
        return acCompanyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_company.ac_company_name
     *
     * @param acCompanyName the value for ac_company.ac_company_name
     *
     * @mbggenerated
     */
    public void setAcCompanyName(String acCompanyName) {
        this.acCompanyName = acCompanyName == null ? null : acCompanyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_company.ac_company_url
     *
     * @return the value of ac_company.ac_company_url
     *
     * @mbggenerated
     */
    public String getAcCompanyUrl() {
        return acCompanyUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_company.ac_company_url
     *
     * @param acCompanyUrl the value for ac_company.ac_company_url
     *
     * @mbggenerated
     */
    public void setAcCompanyUrl(String acCompanyUrl) {
        this.acCompanyUrl = acCompanyUrl == null ? null : acCompanyUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_company.ac_company_logo
     *
     * @return the value of ac_company.ac_company_logo
     *
     * @mbggenerated
     */
    public String getAcCompanyLogo() {
        return acCompanyLogo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_company.ac_company_logo
     *
     * @param acCompanyLogo the value for ac_company.ac_company_logo
     *
     * @mbggenerated
     */
    public void setAcCompanyLogo(String acCompanyLogo) {
        this.acCompanyLogo = acCompanyLogo == null ? null : acCompanyLogo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_company.ac_company_type
     *
     * @return the value of ac_company.ac_company_type
     *
     * @mbggenerated
     */
    public String getAcCompanyType() {
        return acCompanyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_company.ac_company_type
     *
     * @param acCompanyType the value for ac_company.ac_company_type
     *
     * @mbggenerated
     */
    public void setAcCompanyType(String acCompanyType) {
        this.acCompanyType = acCompanyType == null ? null : acCompanyType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_company.ac_company_context
     *
     * @return the value of ac_company.ac_company_context
     *
     * @mbggenerated
     */
    public String getAcCompanyContext() {
        return acCompanyContext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_company.ac_company_context
     *
     * @param acCompanyContext the value for ac_company.ac_company_context
     *
     * @mbggenerated
     */
    public void setAcCompanyContext(String acCompanyContext) {
        this.acCompanyContext = acCompanyContext == null ? null : acCompanyContext.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_company
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ac_company other = (ac_company) that;
        return (this.getAcCompanyId() == null ? other.getAcCompanyId() == null : this.getAcCompanyId().equals(other.getAcCompanyId()))
            && (this.getAcCompanyName() == null ? other.getAcCompanyName() == null : this.getAcCompanyName().equals(other.getAcCompanyName()))
            && (this.getAcCompanyUrl() == null ? other.getAcCompanyUrl() == null : this.getAcCompanyUrl().equals(other.getAcCompanyUrl()))
            && (this.getAcCompanyLogo() == null ? other.getAcCompanyLogo() == null : this.getAcCompanyLogo().equals(other.getAcCompanyLogo()))
            && (this.getAcCompanyType() == null ? other.getAcCompanyType() == null : this.getAcCompanyType().equals(other.getAcCompanyType()))
            && (this.getAcCompanyContext() == null ? other.getAcCompanyContext() == null : this.getAcCompanyContext().equals(other.getAcCompanyContext()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_company
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getAcCompanyId() == null) ? 0 : getAcCompanyId().hashCode());
        result = prime * result + ((getAcCompanyName() == null) ? 0 : getAcCompanyName().hashCode());
        result = prime * result + ((getAcCompanyUrl() == null) ? 0 : getAcCompanyUrl().hashCode());
        result = prime * result + ((getAcCompanyLogo() == null) ? 0 : getAcCompanyLogo().hashCode());
        result = prime * result + ((getAcCompanyType() == null) ? 0 : getAcCompanyType().hashCode());
        result = prime * result + ((getAcCompanyContext() == null) ? 0 : getAcCompanyContext().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_company
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", acCompanyId=").append(acCompanyId);
        sb.append(", acCompanyName=").append(acCompanyName);
        sb.append(", acCompanyUrl=").append(acCompanyUrl);
        sb.append(", acCompanyLogo=").append(acCompanyLogo);
        sb.append(", acCompanyType=").append(acCompanyType);
        sb.append(", acCompanyContext=").append(acCompanyContext);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}