package com.artclub.model;

import java.io.Serializable;

public class ac_course_video implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_course_video.ac_video_course_id
     *
     * @mbggenerated
     */
    private Integer acVideoCourseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_course_video.ac_video_course_url
     *
     * @mbggenerated
     */
    private String acVideoCourseUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_course_video.ac_video_course_courseid
     *
     * @mbggenerated
     */
    private Integer acVideoCourseCourseid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_course_video.ac_video_course_time
     *
     * @mbggenerated
     */
    private String acVideoCourseTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_course_video.ac_video_course_status
     *
     * @mbggenerated
     */
    private Integer acVideoCourseStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_course_video.ac_video_course_likes
     *
     * @mbggenerated
     */
    private String acVideoCourseLikes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_course_video.ac_video_course_title
     *
     * @mbggenerated
     */
    private String acVideoCourseTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_course_video.ac_video_course_Chapter
     *
     * @mbggenerated
     */
    private String acVideoCourseChapter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_course_video.ac_video_course_episode
     *
     * @mbggenerated
     */
    private String acVideoCourseEpisode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_course_video.ac_video_course_parentChapter
     *
     * @mbggenerated
     */
    private String acVideoCourseParentchapter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_course_video.ac_video_course_file
     *
     * @mbggenerated
     */
    private String acVideoCourseFile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ac_course_video
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_course_video.ac_video_course_id
     *
     * @return the value of ac_course_video.ac_video_course_id
     *
     * @mbggenerated
     */
    public Integer getAcVideoCourseId() {
        return acVideoCourseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_course_video.ac_video_course_id
     *
     * @param acVideoCourseId the value for ac_course_video.ac_video_course_id
     *
     * @mbggenerated
     */
    public void setAcVideoCourseId(Integer acVideoCourseId) {
        this.acVideoCourseId = acVideoCourseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_course_video.ac_video_course_url
     *
     * @return the value of ac_course_video.ac_video_course_url
     *
     * @mbggenerated
     */
    public String getAcVideoCourseUrl() {
        return acVideoCourseUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_course_video.ac_video_course_url
     *
     * @param acVideoCourseUrl the value for ac_course_video.ac_video_course_url
     *
     * @mbggenerated
     */
    public void setAcVideoCourseUrl(String acVideoCourseUrl) {
        this.acVideoCourseUrl = acVideoCourseUrl == null ? null : acVideoCourseUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_course_video.ac_video_course_courseid
     *
     * @return the value of ac_course_video.ac_video_course_courseid
     *
     * @mbggenerated
     */
    public Integer getAcVideoCourseCourseid() {
        return acVideoCourseCourseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_course_video.ac_video_course_courseid
     *
     * @param acVideoCourseCourseid the value for ac_course_video.ac_video_course_courseid
     *
     * @mbggenerated
     */
    public void setAcVideoCourseCourseid(Integer acVideoCourseCourseid) {
        this.acVideoCourseCourseid = acVideoCourseCourseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_course_video.ac_video_course_time
     *
     * @return the value of ac_course_video.ac_video_course_time
     *
     * @mbggenerated
     */
    public String getAcVideoCourseTime() {
        return acVideoCourseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_course_video.ac_video_course_time
     *
     * @param acVideoCourseTime the value for ac_course_video.ac_video_course_time
     *
     * @mbggenerated
     */
    public void setAcVideoCourseTime(String acVideoCourseTime) {
        this.acVideoCourseTime = acVideoCourseTime == null ? null : acVideoCourseTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_course_video.ac_video_course_status
     *
     * @return the value of ac_course_video.ac_video_course_status
     *
     * @mbggenerated
     */
    public Integer getAcVideoCourseStatus() {
        return acVideoCourseStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_course_video.ac_video_course_status
     *
     * @param acVideoCourseStatus the value for ac_course_video.ac_video_course_status
     *
     * @mbggenerated
     */
    public void setAcVideoCourseStatus(Integer acVideoCourseStatus) {
        this.acVideoCourseStatus = acVideoCourseStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_course_video.ac_video_course_likes
     *
     * @return the value of ac_course_video.ac_video_course_likes
     *
     * @mbggenerated
     */
    public String getAcVideoCourseLikes() {
        return acVideoCourseLikes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_course_video.ac_video_course_likes
     *
     * @param acVideoCourseLikes the value for ac_course_video.ac_video_course_likes
     *
     * @mbggenerated
     */
    public void setAcVideoCourseLikes(String acVideoCourseLikes) {
        this.acVideoCourseLikes = acVideoCourseLikes == null ? null : acVideoCourseLikes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_course_video.ac_video_course_title
     *
     * @return the value of ac_course_video.ac_video_course_title
     *
     * @mbggenerated
     */
    public String getAcVideoCourseTitle() {
        return acVideoCourseTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_course_video.ac_video_course_title
     *
     * @param acVideoCourseTitle the value for ac_course_video.ac_video_course_title
     *
     * @mbggenerated
     */
    public void setAcVideoCourseTitle(String acVideoCourseTitle) {
        this.acVideoCourseTitle = acVideoCourseTitle == null ? null : acVideoCourseTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_course_video.ac_video_course_Chapter
     *
     * @return the value of ac_course_video.ac_video_course_Chapter
     *
     * @mbggenerated
     */
    public String getAcVideoCourseChapter() {
        return acVideoCourseChapter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_course_video.ac_video_course_Chapter
     *
     * @param acVideoCourseChapter the value for ac_course_video.ac_video_course_Chapter
     *
     * @mbggenerated
     */
    public void setAcVideoCourseChapter(String acVideoCourseChapter) {
        this.acVideoCourseChapter = acVideoCourseChapter == null ? null : acVideoCourseChapter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_course_video.ac_video_course_episode
     *
     * @return the value of ac_course_video.ac_video_course_episode
     *
     * @mbggenerated
     */
    public String getAcVideoCourseEpisode() {
        return acVideoCourseEpisode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_course_video.ac_video_course_episode
     *
     * @param acVideoCourseEpisode the value for ac_course_video.ac_video_course_episode
     *
     * @mbggenerated
     */
    public void setAcVideoCourseEpisode(String acVideoCourseEpisode) {
        this.acVideoCourseEpisode = acVideoCourseEpisode == null ? null : acVideoCourseEpisode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_course_video.ac_video_course_parentChapter
     *
     * @return the value of ac_course_video.ac_video_course_parentChapter
     *
     * @mbggenerated
     */
    public String getAcVideoCourseParentchapter() {
        return acVideoCourseParentchapter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_course_video.ac_video_course_parentChapter
     *
     * @param acVideoCourseParentchapter the value for ac_course_video.ac_video_course_parentChapter
     *
     * @mbggenerated
     */
    public void setAcVideoCourseParentchapter(String acVideoCourseParentchapter) {
        this.acVideoCourseParentchapter = acVideoCourseParentchapter == null ? null : acVideoCourseParentchapter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_course_video.ac_video_course_file
     *
     * @return the value of ac_course_video.ac_video_course_file
     *
     * @mbggenerated
     */
    public String getAcVideoCourseFile() {
        return acVideoCourseFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_course_video.ac_video_course_file
     *
     * @param acVideoCourseFile the value for ac_course_video.ac_video_course_file
     *
     * @mbggenerated
     */
    public void setAcVideoCourseFile(String acVideoCourseFile) {
        this.acVideoCourseFile = acVideoCourseFile == null ? null : acVideoCourseFile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_course_video
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ac_course_video other = (ac_course_video) that;
        return (this.getAcVideoCourseId() == null ? other.getAcVideoCourseId() == null : this.getAcVideoCourseId().equals(other.getAcVideoCourseId()))
            && (this.getAcVideoCourseUrl() == null ? other.getAcVideoCourseUrl() == null : this.getAcVideoCourseUrl().equals(other.getAcVideoCourseUrl()))
            && (this.getAcVideoCourseCourseid() == null ? other.getAcVideoCourseCourseid() == null : this.getAcVideoCourseCourseid().equals(other.getAcVideoCourseCourseid()))
            && (this.getAcVideoCourseTime() == null ? other.getAcVideoCourseTime() == null : this.getAcVideoCourseTime().equals(other.getAcVideoCourseTime()))
            && (this.getAcVideoCourseStatus() == null ? other.getAcVideoCourseStatus() == null : this.getAcVideoCourseStatus().equals(other.getAcVideoCourseStatus()))
            && (this.getAcVideoCourseLikes() == null ? other.getAcVideoCourseLikes() == null : this.getAcVideoCourseLikes().equals(other.getAcVideoCourseLikes()))
            && (this.getAcVideoCourseTitle() == null ? other.getAcVideoCourseTitle() == null : this.getAcVideoCourseTitle().equals(other.getAcVideoCourseTitle()))
            && (this.getAcVideoCourseChapter() == null ? other.getAcVideoCourseChapter() == null : this.getAcVideoCourseChapter().equals(other.getAcVideoCourseChapter()))
            && (this.getAcVideoCourseEpisode() == null ? other.getAcVideoCourseEpisode() == null : this.getAcVideoCourseEpisode().equals(other.getAcVideoCourseEpisode()))
            && (this.getAcVideoCourseParentchapter() == null ? other.getAcVideoCourseParentchapter() == null : this.getAcVideoCourseParentchapter().equals(other.getAcVideoCourseParentchapter()))
            && (this.getAcVideoCourseFile() == null ? other.getAcVideoCourseFile() == null : this.getAcVideoCourseFile().equals(other.getAcVideoCourseFile()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_course_video
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getAcVideoCourseId() == null) ? 0 : getAcVideoCourseId().hashCode());
        result = prime * result + ((getAcVideoCourseUrl() == null) ? 0 : getAcVideoCourseUrl().hashCode());
        result = prime * result + ((getAcVideoCourseCourseid() == null) ? 0 : getAcVideoCourseCourseid().hashCode());
        result = prime * result + ((getAcVideoCourseTime() == null) ? 0 : getAcVideoCourseTime().hashCode());
        result = prime * result + ((getAcVideoCourseStatus() == null) ? 0 : getAcVideoCourseStatus().hashCode());
        result = prime * result + ((getAcVideoCourseLikes() == null) ? 0 : getAcVideoCourseLikes().hashCode());
        result = prime * result + ((getAcVideoCourseTitle() == null) ? 0 : getAcVideoCourseTitle().hashCode());
        result = prime * result + ((getAcVideoCourseChapter() == null) ? 0 : getAcVideoCourseChapter().hashCode());
        result = prime * result + ((getAcVideoCourseEpisode() == null) ? 0 : getAcVideoCourseEpisode().hashCode());
        result = prime * result + ((getAcVideoCourseParentchapter() == null) ? 0 : getAcVideoCourseParentchapter().hashCode());
        result = prime * result + ((getAcVideoCourseFile() == null) ? 0 : getAcVideoCourseFile().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_course_video
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", acVideoCourseId=").append(acVideoCourseId);
        sb.append(", acVideoCourseUrl=").append(acVideoCourseUrl);
        sb.append(", acVideoCourseCourseid=").append(acVideoCourseCourseid);
        sb.append(", acVideoCourseTime=").append(acVideoCourseTime);
        sb.append(", acVideoCourseStatus=").append(acVideoCourseStatus);
        sb.append(", acVideoCourseLikes=").append(acVideoCourseLikes);
        sb.append(", acVideoCourseTitle=").append(acVideoCourseTitle);
        sb.append(", acVideoCourseChapter=").append(acVideoCourseChapter);
        sb.append(", acVideoCourseEpisode=").append(acVideoCourseEpisode);
        sb.append(", acVideoCourseParentchapter=").append(acVideoCourseParentchapter);
        sb.append(", acVideoCourseFile=").append(acVideoCourseFile);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}