package com.artclub.model;

import java.io.Serializable;

public class ac_dictionary implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_dictionary.ac_dictionary_id
     *
     * @mbggenerated
     */
    private Integer acDictionaryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_dictionary.ac_dictionary_status
     *
     * @mbggenerated
     */
    private String acDictionaryStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_dictionary.ac_dictionary_statusCode
     *
     * @mbggenerated
     */
    private Integer acDictionaryStatuscode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_dictionary.ac_dictionary_table
     *
     * @mbggenerated
     */
    private String acDictionaryTable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ac_dictionary
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_dictionary.ac_dictionary_id
     *
     * @return the value of ac_dictionary.ac_dictionary_id
     *
     * @mbggenerated
     */
    public Integer getAcDictionaryId() {
        return acDictionaryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_dictionary.ac_dictionary_id
     *
     * @param acDictionaryId the value for ac_dictionary.ac_dictionary_id
     *
     * @mbggenerated
     */
    public void setAcDictionaryId(Integer acDictionaryId) {
        this.acDictionaryId = acDictionaryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_dictionary.ac_dictionary_status
     *
     * @return the value of ac_dictionary.ac_dictionary_status
     *
     * @mbggenerated
     */
    public String getAcDictionaryStatus() {
        return acDictionaryStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_dictionary.ac_dictionary_status
     *
     * @param acDictionaryStatus the value for ac_dictionary.ac_dictionary_status
     *
     * @mbggenerated
     */
    public void setAcDictionaryStatus(String acDictionaryStatus) {
        this.acDictionaryStatus = acDictionaryStatus == null ? null : acDictionaryStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_dictionary.ac_dictionary_statusCode
     *
     * @return the value of ac_dictionary.ac_dictionary_statusCode
     *
     * @mbggenerated
     */
    public Integer getAcDictionaryStatuscode() {
        return acDictionaryStatuscode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_dictionary.ac_dictionary_statusCode
     *
     * @param acDictionaryStatuscode the value for ac_dictionary.ac_dictionary_statusCode
     *
     * @mbggenerated
     */
    public void setAcDictionaryStatuscode(Integer acDictionaryStatuscode) {
        this.acDictionaryStatuscode = acDictionaryStatuscode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_dictionary.ac_dictionary_table
     *
     * @return the value of ac_dictionary.ac_dictionary_table
     *
     * @mbggenerated
     */
    public String getAcDictionaryTable() {
        return acDictionaryTable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_dictionary.ac_dictionary_table
     *
     * @param acDictionaryTable the value for ac_dictionary.ac_dictionary_table
     *
     * @mbggenerated
     */
    public void setAcDictionaryTable(String acDictionaryTable) {
        this.acDictionaryTable = acDictionaryTable == null ? null : acDictionaryTable.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_dictionary
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ac_dictionary other = (ac_dictionary) that;
        return (this.getAcDictionaryId() == null ? other.getAcDictionaryId() == null : this.getAcDictionaryId().equals(other.getAcDictionaryId()))
            && (this.getAcDictionaryStatus() == null ? other.getAcDictionaryStatus() == null : this.getAcDictionaryStatus().equals(other.getAcDictionaryStatus()))
            && (this.getAcDictionaryStatuscode() == null ? other.getAcDictionaryStatuscode() == null : this.getAcDictionaryStatuscode().equals(other.getAcDictionaryStatuscode()))
            && (this.getAcDictionaryTable() == null ? other.getAcDictionaryTable() == null : this.getAcDictionaryTable().equals(other.getAcDictionaryTable()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_dictionary
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getAcDictionaryId() == null) ? 0 : getAcDictionaryId().hashCode());
        result = prime * result + ((getAcDictionaryStatus() == null) ? 0 : getAcDictionaryStatus().hashCode());
        result = prime * result + ((getAcDictionaryStatuscode() == null) ? 0 : getAcDictionaryStatuscode().hashCode());
        result = prime * result + ((getAcDictionaryTable() == null) ? 0 : getAcDictionaryTable().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_dictionary
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", acDictionaryId=").append(acDictionaryId);
        sb.append(", acDictionaryStatus=").append(acDictionaryStatus);
        sb.append(", acDictionaryStatuscode=").append(acDictionaryStatuscode);
        sb.append(", acDictionaryTable=").append(acDictionaryTable);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}