package com.artclub.model;

import java.io.Serializable;

public class ac_instrument implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_instrument.ac_instrument_id
     *
     * @mbggenerated
     */
    private Integer acInstrumentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_instrument.ac_instrument_name
     *
     * @mbggenerated
     */
    private String acInstrumentName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_instrument.ac_instrument_context
     *
     * @mbggenerated
     */
    private String acInstrumentContext;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_instrument.ac_instrument_addtime
     *
     * @mbggenerated
     */
    private String acInstrumentAddtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_instrument.ac_instrument_typeId
     *
     * @mbggenerated
     */
    private String acInstrumentTypeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ac_instrument
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_instrument.ac_instrument_id
     *
     * @return the value of ac_instrument.ac_instrument_id
     *
     * @mbggenerated
     */
    public Integer getAcInstrumentId() {
        return acInstrumentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_instrument.ac_instrument_id
     *
     * @param acInstrumentId the value for ac_instrument.ac_instrument_id
     *
     * @mbggenerated
     */
    public void setAcInstrumentId(Integer acInstrumentId) {
        this.acInstrumentId = acInstrumentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_instrument.ac_instrument_name
     *
     * @return the value of ac_instrument.ac_instrument_name
     *
     * @mbggenerated
     */
    public String getAcInstrumentName() {
        return acInstrumentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_instrument.ac_instrument_name
     *
     * @param acInstrumentName the value for ac_instrument.ac_instrument_name
     *
     * @mbggenerated
     */
    public void setAcInstrumentName(String acInstrumentName) {
        this.acInstrumentName = acInstrumentName == null ? null : acInstrumentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_instrument.ac_instrument_context
     *
     * @return the value of ac_instrument.ac_instrument_context
     *
     * @mbggenerated
     */
    public String getAcInstrumentContext() {
        return acInstrumentContext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_instrument.ac_instrument_context
     *
     * @param acInstrumentContext the value for ac_instrument.ac_instrument_context
     *
     * @mbggenerated
     */
    public void setAcInstrumentContext(String acInstrumentContext) {
        this.acInstrumentContext = acInstrumentContext == null ? null : acInstrumentContext.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_instrument.ac_instrument_addtime
     *
     * @return the value of ac_instrument.ac_instrument_addtime
     *
     * @mbggenerated
     */
    public String getAcInstrumentAddtime() {
        return acInstrumentAddtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_instrument.ac_instrument_addtime
     *
     * @param acInstrumentAddtime the value for ac_instrument.ac_instrument_addtime
     *
     * @mbggenerated
     */
    public void setAcInstrumentAddtime(String acInstrumentAddtime) {
        this.acInstrumentAddtime = acInstrumentAddtime == null ? null : acInstrumentAddtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_instrument.ac_instrument_typeId
     *
     * @return the value of ac_instrument.ac_instrument_typeId
     *
     * @mbggenerated
     */
    public String getAcInstrumentTypeid() {
        return acInstrumentTypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_instrument.ac_instrument_typeId
     *
     * @param acInstrumentTypeid the value for ac_instrument.ac_instrument_typeId
     *
     * @mbggenerated
     */
    public void setAcInstrumentTypeid(String acInstrumentTypeid) {
        this.acInstrumentTypeid = acInstrumentTypeid == null ? null : acInstrumentTypeid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_instrument
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ac_instrument other = (ac_instrument) that;
        return (this.getAcInstrumentId() == null ? other.getAcInstrumentId() == null : this.getAcInstrumentId().equals(other.getAcInstrumentId()))
            && (this.getAcInstrumentName() == null ? other.getAcInstrumentName() == null : this.getAcInstrumentName().equals(other.getAcInstrumentName()))
            && (this.getAcInstrumentContext() == null ? other.getAcInstrumentContext() == null : this.getAcInstrumentContext().equals(other.getAcInstrumentContext()))
            && (this.getAcInstrumentAddtime() == null ? other.getAcInstrumentAddtime() == null : this.getAcInstrumentAddtime().equals(other.getAcInstrumentAddtime()))
            && (this.getAcInstrumentTypeid() == null ? other.getAcInstrumentTypeid() == null : this.getAcInstrumentTypeid().equals(other.getAcInstrumentTypeid()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_instrument
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getAcInstrumentId() == null) ? 0 : getAcInstrumentId().hashCode());
        result = prime * result + ((getAcInstrumentName() == null) ? 0 : getAcInstrumentName().hashCode());
        result = prime * result + ((getAcInstrumentContext() == null) ? 0 : getAcInstrumentContext().hashCode());
        result = prime * result + ((getAcInstrumentAddtime() == null) ? 0 : getAcInstrumentAddtime().hashCode());
        result = prime * result + ((getAcInstrumentTypeid() == null) ? 0 : getAcInstrumentTypeid().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_instrument
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", acInstrumentId=").append(acInstrumentId);
        sb.append(", acInstrumentName=").append(acInstrumentName);
        sb.append(", acInstrumentContext=").append(acInstrumentContext);
        sb.append(", acInstrumentAddtime=").append(acInstrumentAddtime);
        sb.append(", acInstrumentTypeid=").append(acInstrumentTypeid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}