package com.artclub.model;

import java.io.Serializable;

public class ac_message implements Serializable {
    String FromName;
    String ToUser;
    String ftime;

    public String getFtime() {
        return ftime;
    }

    public void setFtime(String ftime) {
        this.ftime = ftime;
    }

    public String getFromName() {
        return FromName;
    }

    public void setFromName(String fromName) {
        FromName = fromName;
    }

    public String getToUser() {
        return ToUser;
    }

    public void setToUser(String toUser) {
        ToUser = toUser;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_message.ac_message_id
     *
     * @mbggenerated
     */
    private Integer acMessageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_message.ac_message_message
     *
     * @mbggenerated
     */
    private String acMessageMessage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_message.ac_message_from
     *
     * @mbggenerated
     */
    private String acMessageFrom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_message.ac_message_to
     *
     * @mbggenerated
     */
    private String acMessageTo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_message.ac_message_addtime
     *
     * @mbggenerated
     */
    private String acMessageAddtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_message.ac_message_status
     *
     * @mbggenerated
     */
    private String acMessageStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ac_message
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_message.ac_message_id
     *
     * @return the value of ac_message.ac_message_id
     * @mbggenerated
     */
    public Integer getAcMessageId() {
        return acMessageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_message.ac_message_id
     *
     * @param acMessageId the value for ac_message.ac_message_id
     * @mbggenerated
     */
    public void setAcMessageId(Integer acMessageId) {
        this.acMessageId = acMessageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_message.ac_message_message
     *
     * @return the value of ac_message.ac_message_message
     * @mbggenerated
     */
    public String getAcMessageMessage() {
        return acMessageMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_message.ac_message_message
     *
     * @param acMessageMessage the value for ac_message.ac_message_message
     * @mbggenerated
     */
    public void setAcMessageMessage(String acMessageMessage) {
        this.acMessageMessage = acMessageMessage == null ? null : acMessageMessage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_message.ac_message_from
     *
     * @return the value of ac_message.ac_message_from
     * @mbggenerated
     */
    public String getAcMessageFrom() {
        return acMessageFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_message.ac_message_from
     *
     * @param acMessageFrom the value for ac_message.ac_message_from
     * @mbggenerated
     */
    public void setAcMessageFrom(String acMessageFrom) {
        this.acMessageFrom = acMessageFrom == null ? null : acMessageFrom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_message.ac_message_to
     *
     * @return the value of ac_message.ac_message_to
     * @mbggenerated
     */
    public String getAcMessageTo() {
        return acMessageTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_message.ac_message_to
     *
     * @param acMessageTo the value for ac_message.ac_message_to
     * @mbggenerated
     */
    public void setAcMessageTo(String acMessageTo) {
        this.acMessageTo = acMessageTo == null ? null : acMessageTo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_message.ac_message_addtime
     *
     * @return the value of ac_message.ac_message_addtime
     * @mbggenerated
     */
    public String getAcMessageAddtime() {
        return acMessageAddtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_message.ac_message_addtime
     *
     * @param acMessageAddtime the value for ac_message.ac_message_addtime
     * @mbggenerated
     */
    public void setAcMessageAddtime(String acMessageAddtime) {
        this.acMessageAddtime = acMessageAddtime == null ? null : acMessageAddtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_message.ac_message_status
     *
     * @return the value of ac_message.ac_message_status
     * @mbggenerated
     */
    public String getAcMessageStatus() {
        return acMessageStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_message.ac_message_status
     *
     * @param acMessageStatus the value for ac_message.ac_message_status
     * @mbggenerated
     */
    public void setAcMessageStatus(String acMessageStatus) {
        this.acMessageStatus = acMessageStatus == null ? null : acMessageStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_message
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ac_message other = (ac_message) that;
        return (this.getAcMessageId() == null ? other.getAcMessageId() == null : this.getAcMessageId().equals(other.getAcMessageId())) && (this.getAcMessageMessage() == null ? other.getAcMessageMessage() == null : this.getAcMessageMessage().equals(other.getAcMessageMessage())) && (this.getAcMessageFrom() == null ? other.getAcMessageFrom() == null : this.getAcMessageFrom().equals(other.getAcMessageFrom())) && (this.getAcMessageTo() == null ? other.getAcMessageTo() == null : this.getAcMessageTo().equals(other.getAcMessageTo())) && (this.getAcMessageAddtime() == null ? other.getAcMessageAddtime() == null : this.getAcMessageAddtime().equals(other.getAcMessageAddtime())) && (this.getAcMessageStatus() == null ? other.getAcMessageStatus() == null : this.getAcMessageStatus().equals(other.getAcMessageStatus()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_message
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getAcMessageId() == null) ? 0 : getAcMessageId().hashCode());
        result = prime * result + ((getAcMessageMessage() == null) ? 0 : getAcMessageMessage().hashCode());
        result = prime * result + ((getAcMessageFrom() == null) ? 0 : getAcMessageFrom().hashCode());
        result = prime * result + ((getAcMessageTo() == null) ? 0 : getAcMessageTo().hashCode());
        result = prime * result + ((getAcMessageAddtime() == null) ? 0 : getAcMessageAddtime().hashCode());
        result = prime * result + ((getAcMessageStatus() == null) ? 0 : getAcMessageStatus().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_message
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", acMessageId=").append(acMessageId);
        sb.append(", acMessageMessage=").append(acMessageMessage);
        sb.append(", acMessageFrom=").append(acMessageFrom);
        sb.append(", acMessageTo=").append(acMessageTo);
        sb.append(", acMessageAddtime=").append(acMessageAddtime);
        sb.append(", acMessageStatus=").append(acMessageStatus);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}