package com.artclub.model;

import java.io.Serializable;

public class ac_order implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_order.ac_order_id
     *
     * @mbggenerated
     */
    private Integer acOrderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_order.ac_order_userId
     *
     * @mbggenerated
     */
    private Integer acOrderUserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_order.ac_order_courseId
     *
     * @mbggenerated
     */
    private Integer acOrderCourseid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_order.ac_order_price
     *
     * @mbggenerated
     */
    private String acOrderPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_order.ac_order_addtime
     *
     * @mbggenerated
     */
    private String acOrderAddtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_order.ac_order_status
     *
     * @mbggenerated
     */
    private String acOrderStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ac_order
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_order.ac_order_id
     *
     * @return the value of ac_order.ac_order_id
     *
     * @mbggenerated
     */
    public Integer getAcOrderId() {
        return acOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_order.ac_order_id
     *
     * @param acOrderId the value for ac_order.ac_order_id
     *
     * @mbggenerated
     */
    public void setAcOrderId(Integer acOrderId) {
        this.acOrderId = acOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_order.ac_order_userId
     *
     * @return the value of ac_order.ac_order_userId
     *
     * @mbggenerated
     */
    public Integer getAcOrderUserid() {
        return acOrderUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_order.ac_order_userId
     *
     * @param acOrderUserid the value for ac_order.ac_order_userId
     *
     * @mbggenerated
     */
    public void setAcOrderUserid(Integer acOrderUserid) {
        this.acOrderUserid = acOrderUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_order.ac_order_courseId
     *
     * @return the value of ac_order.ac_order_courseId
     *
     * @mbggenerated
     */
    public Integer getAcOrderCourseid() {
        return acOrderCourseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_order.ac_order_courseId
     *
     * @param acOrderCourseid the value for ac_order.ac_order_courseId
     *
     * @mbggenerated
     */
    public void setAcOrderCourseid(Integer acOrderCourseid) {
        this.acOrderCourseid = acOrderCourseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_order.ac_order_price
     *
     * @return the value of ac_order.ac_order_price
     *
     * @mbggenerated
     */
    public String getAcOrderPrice() {
        return acOrderPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_order.ac_order_price
     *
     * @param acOrderPrice the value for ac_order.ac_order_price
     *
     * @mbggenerated
     */
    public void setAcOrderPrice(String acOrderPrice) {
        this.acOrderPrice = acOrderPrice == null ? null : acOrderPrice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_order.ac_order_addtime
     *
     * @return the value of ac_order.ac_order_addtime
     *
     * @mbggenerated
     */
    public String getAcOrderAddtime() {
        return acOrderAddtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_order.ac_order_addtime
     *
     * @param acOrderAddtime the value for ac_order.ac_order_addtime
     *
     * @mbggenerated
     */
    public void setAcOrderAddtime(String acOrderAddtime) {
        this.acOrderAddtime = acOrderAddtime == null ? null : acOrderAddtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_order.ac_order_status
     *
     * @return the value of ac_order.ac_order_status
     *
     * @mbggenerated
     */
    public String getAcOrderStatus() {
        return acOrderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_order.ac_order_status
     *
     * @param acOrderStatus the value for ac_order.ac_order_status
     *
     * @mbggenerated
     */
    public void setAcOrderStatus(String acOrderStatus) {
        this.acOrderStatus = acOrderStatus == null ? null : acOrderStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_order
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ac_order other = (ac_order) that;
        return (this.getAcOrderId() == null ? other.getAcOrderId() == null : this.getAcOrderId().equals(other.getAcOrderId()))
            && (this.getAcOrderUserid() == null ? other.getAcOrderUserid() == null : this.getAcOrderUserid().equals(other.getAcOrderUserid()))
            && (this.getAcOrderCourseid() == null ? other.getAcOrderCourseid() == null : this.getAcOrderCourseid().equals(other.getAcOrderCourseid()))
            && (this.getAcOrderPrice() == null ? other.getAcOrderPrice() == null : this.getAcOrderPrice().equals(other.getAcOrderPrice()))
            && (this.getAcOrderAddtime() == null ? other.getAcOrderAddtime() == null : this.getAcOrderAddtime().equals(other.getAcOrderAddtime()))
            && (this.getAcOrderStatus() == null ? other.getAcOrderStatus() == null : this.getAcOrderStatus().equals(other.getAcOrderStatus()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_order
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getAcOrderId() == null) ? 0 : getAcOrderId().hashCode());
        result = prime * result + ((getAcOrderUserid() == null) ? 0 : getAcOrderUserid().hashCode());
        result = prime * result + ((getAcOrderCourseid() == null) ? 0 : getAcOrderCourseid().hashCode());
        result = prime * result + ((getAcOrderPrice() == null) ? 0 : getAcOrderPrice().hashCode());
        result = prime * result + ((getAcOrderAddtime() == null) ? 0 : getAcOrderAddtime().hashCode());
        result = prime * result + ((getAcOrderStatus() == null) ? 0 : getAcOrderStatus().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_order
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", acOrderId=").append(acOrderId);
        sb.append(", acOrderUserid=").append(acOrderUserid);
        sb.append(", acOrderCourseid=").append(acOrderCourseid);
        sb.append(", acOrderPrice=").append(acOrderPrice);
        sb.append(", acOrderAddtime=").append(acOrderAddtime);
        sb.append(", acOrderStatus=").append(acOrderStatus);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}