package com.artclub.model;

import java.io.Serializable;

public class ac_outresume implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_outresume.ac_outresume_id
     *
     * @mbggenerated
     */
    private Integer acOutresumeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_outresume.ac_outresume_context
     *
     * @mbggenerated
     */
    private String acOutresumeContext;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_outresume.ac_outresume_url
     *
     * @mbggenerated
     */
    private String acOutresumeUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_outresume.ac_outresume_author
     *
     * @mbggenerated
     */
    private String acOutresumeAuthor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_outresume.ac_outresume_phoneNumber
     *
     * @mbggenerated
     */
    private String acOutresumePhonenumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_outresume.ac_outresume_email
     *
     * @mbggenerated
     */
    private String acOutresumeEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_outresume.ac_outresume_time
     *
     * @mbggenerated
     */
    private String acOutresumeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_outresume.ac_outresume_status
     *
     * @mbggenerated
     */
    private Integer acOutresumeStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ac_outresume
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_outresume.ac_outresume_id
     *
     * @return the value of ac_outresume.ac_outresume_id
     *
     * @mbggenerated
     */
    public Integer getAcOutresumeId() {
        return acOutresumeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_outresume.ac_outresume_id
     *
     * @param acOutresumeId the value for ac_outresume.ac_outresume_id
     *
     * @mbggenerated
     */
    public void setAcOutresumeId(Integer acOutresumeId) {
        this.acOutresumeId = acOutresumeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_outresume.ac_outresume_context
     *
     * @return the value of ac_outresume.ac_outresume_context
     *
     * @mbggenerated
     */
    public String getAcOutresumeContext() {
        return acOutresumeContext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_outresume.ac_outresume_context
     *
     * @param acOutresumeContext the value for ac_outresume.ac_outresume_context
     *
     * @mbggenerated
     */
    public void setAcOutresumeContext(String acOutresumeContext) {
        this.acOutresumeContext = acOutresumeContext == null ? null : acOutresumeContext.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_outresume.ac_outresume_url
     *
     * @return the value of ac_outresume.ac_outresume_url
     *
     * @mbggenerated
     */
    public String getAcOutresumeUrl() {
        return acOutresumeUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_outresume.ac_outresume_url
     *
     * @param acOutresumeUrl the value for ac_outresume.ac_outresume_url
     *
     * @mbggenerated
     */
    public void setAcOutresumeUrl(String acOutresumeUrl) {
        this.acOutresumeUrl = acOutresumeUrl == null ? null : acOutresumeUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_outresume.ac_outresume_author
     *
     * @return the value of ac_outresume.ac_outresume_author
     *
     * @mbggenerated
     */
    public String getAcOutresumeAuthor() {
        return acOutresumeAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_outresume.ac_outresume_author
     *
     * @param acOutresumeAuthor the value for ac_outresume.ac_outresume_author
     *
     * @mbggenerated
     */
    public void setAcOutresumeAuthor(String acOutresumeAuthor) {
        this.acOutresumeAuthor = acOutresumeAuthor == null ? null : acOutresumeAuthor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_outresume.ac_outresume_phoneNumber
     *
     * @return the value of ac_outresume.ac_outresume_phoneNumber
     *
     * @mbggenerated
     */
    public String getAcOutresumePhonenumber() {
        return acOutresumePhonenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_outresume.ac_outresume_phoneNumber
     *
     * @param acOutresumePhonenumber the value for ac_outresume.ac_outresume_phoneNumber
     *
     * @mbggenerated
     */
    public void setAcOutresumePhonenumber(String acOutresumePhonenumber) {
        this.acOutresumePhonenumber = acOutresumePhonenumber == null ? null : acOutresumePhonenumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_outresume.ac_outresume_email
     *
     * @return the value of ac_outresume.ac_outresume_email
     *
     * @mbggenerated
     */
    public String getAcOutresumeEmail() {
        return acOutresumeEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_outresume.ac_outresume_email
     *
     * @param acOutresumeEmail the value for ac_outresume.ac_outresume_email
     *
     * @mbggenerated
     */
    public void setAcOutresumeEmail(String acOutresumeEmail) {
        this.acOutresumeEmail = acOutresumeEmail == null ? null : acOutresumeEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_outresume.ac_outresume_time
     *
     * @return the value of ac_outresume.ac_outresume_time
     *
     * @mbggenerated
     */
    public String getAcOutresumeTime() {
        return acOutresumeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_outresume.ac_outresume_time
     *
     * @param acOutresumeTime the value for ac_outresume.ac_outresume_time
     *
     * @mbggenerated
     */
    public void setAcOutresumeTime(String acOutresumeTime) {
        this.acOutresumeTime = acOutresumeTime == null ? null : acOutresumeTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_outresume.ac_outresume_status
     *
     * @return the value of ac_outresume.ac_outresume_status
     *
     * @mbggenerated
     */
    public Integer getAcOutresumeStatus() {
        return acOutresumeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_outresume.ac_outresume_status
     *
     * @param acOutresumeStatus the value for ac_outresume.ac_outresume_status
     *
     * @mbggenerated
     */
    public void setAcOutresumeStatus(Integer acOutresumeStatus) {
        this.acOutresumeStatus = acOutresumeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_outresume
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ac_outresume other = (ac_outresume) that;
        return (this.getAcOutresumeId() == null ? other.getAcOutresumeId() == null : this.getAcOutresumeId().equals(other.getAcOutresumeId()))
            && (this.getAcOutresumeContext() == null ? other.getAcOutresumeContext() == null : this.getAcOutresumeContext().equals(other.getAcOutresumeContext()))
            && (this.getAcOutresumeUrl() == null ? other.getAcOutresumeUrl() == null : this.getAcOutresumeUrl().equals(other.getAcOutresumeUrl()))
            && (this.getAcOutresumeAuthor() == null ? other.getAcOutresumeAuthor() == null : this.getAcOutresumeAuthor().equals(other.getAcOutresumeAuthor()))
            && (this.getAcOutresumePhonenumber() == null ? other.getAcOutresumePhonenumber() == null : this.getAcOutresumePhonenumber().equals(other.getAcOutresumePhonenumber()))
            && (this.getAcOutresumeEmail() == null ? other.getAcOutresumeEmail() == null : this.getAcOutresumeEmail().equals(other.getAcOutresumeEmail()))
            && (this.getAcOutresumeTime() == null ? other.getAcOutresumeTime() == null : this.getAcOutresumeTime().equals(other.getAcOutresumeTime()))
            && (this.getAcOutresumeStatus() == null ? other.getAcOutresumeStatus() == null : this.getAcOutresumeStatus().equals(other.getAcOutresumeStatus()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_outresume
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getAcOutresumeId() == null) ? 0 : getAcOutresumeId().hashCode());
        result = prime * result + ((getAcOutresumeContext() == null) ? 0 : getAcOutresumeContext().hashCode());
        result = prime * result + ((getAcOutresumeUrl() == null) ? 0 : getAcOutresumeUrl().hashCode());
        result = prime * result + ((getAcOutresumeAuthor() == null) ? 0 : getAcOutresumeAuthor().hashCode());
        result = prime * result + ((getAcOutresumePhonenumber() == null) ? 0 : getAcOutresumePhonenumber().hashCode());
        result = prime * result + ((getAcOutresumeEmail() == null) ? 0 : getAcOutresumeEmail().hashCode());
        result = prime * result + ((getAcOutresumeTime() == null) ? 0 : getAcOutresumeTime().hashCode());
        result = prime * result + ((getAcOutresumeStatus() == null) ? 0 : getAcOutresumeStatus().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_outresume
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", acOutresumeId=").append(acOutresumeId);
        sb.append(", acOutresumeContext=").append(acOutresumeContext);
        sb.append(", acOutresumeUrl=").append(acOutresumeUrl);
        sb.append(", acOutresumeAuthor=").append(acOutresumeAuthor);
        sb.append(", acOutresumePhonenumber=").append(acOutresumePhonenumber);
        sb.append(", acOutresumeEmail=").append(acOutresumeEmail);
        sb.append(", acOutresumeTime=").append(acOutresumeTime);
        sb.append(", acOutresumeStatus=").append(acOutresumeStatus);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}