package com.artclub.model;

import java.io.Serializable;

public class ac_objectCourse implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_objectcourse.ac_objectCourse_id
     *
     * @mbggenerated
     */
    private Integer acObjectcourseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_objectcourse.ac_objectCourse_name
     *
     * @mbggenerated
     */
    private String acObjectcourseName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_objectcourse.ac_objectCourse_context
     *
     * @mbggenerated
     */
    private String acObjectcourseContext;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_objectcourse.ac_objectCourse_addtime
     *
     * @mbggenerated
     */
    private String acObjectcourseAddtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_objectcourse.ac_objectCourse_parentInRelation
     *
     * @mbggenerated
     */
    private String acObjectcourseParentinrelation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ac_objectcourse
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_objectcourse.ac_objectCourse_id
     *
     * @return the value of ac_objectcourse.ac_objectCourse_id
     *
     * @mbggenerated
     */
    public Integer getAcObjectcourseId() {
        return acObjectcourseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_objectcourse.ac_objectCourse_id
     *
     * @param acObjectcourseId the value for ac_objectcourse.ac_objectCourse_id
     *
     * @mbggenerated
     */
    public void setAcObjectcourseId(Integer acObjectcourseId) {
        this.acObjectcourseId = acObjectcourseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_objectcourse.ac_objectCourse_name
     *
     * @return the value of ac_objectcourse.ac_objectCourse_name
     *
     * @mbggenerated
     */
    public String getAcObjectcourseName() {
        return acObjectcourseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_objectcourse.ac_objectCourse_name
     *
     * @param acObjectcourseName the value for ac_objectcourse.ac_objectCourse_name
     *
     * @mbggenerated
     */
    public void setAcObjectcourseName(String acObjectcourseName) {
        this.acObjectcourseName = acObjectcourseName == null ? null : acObjectcourseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_objectcourse.ac_objectCourse_context
     *
     * @return the value of ac_objectcourse.ac_objectCourse_context
     *
     * @mbggenerated
     */
    public String getAcObjectcourseContext() {
        return acObjectcourseContext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_objectcourse.ac_objectCourse_context
     *
     * @param acObjectcourseContext the value for ac_objectcourse.ac_objectCourse_context
     *
     * @mbggenerated
     */
    public void setAcObjectcourseContext(String acObjectcourseContext) {
        this.acObjectcourseContext = acObjectcourseContext == null ? null : acObjectcourseContext.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_objectcourse.ac_objectCourse_addtime
     *
     * @return the value of ac_objectcourse.ac_objectCourse_addtime
     *
     * @mbggenerated
     */
    public String getAcObjectcourseAddtime() {
        return acObjectcourseAddtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_objectcourse.ac_objectCourse_addtime
     *
     * @param acObjectcourseAddtime the value for ac_objectcourse.ac_objectCourse_addtime
     *
     * @mbggenerated
     */
    public void setAcObjectcourseAddtime(String acObjectcourseAddtime) {
        this.acObjectcourseAddtime = acObjectcourseAddtime == null ? null : acObjectcourseAddtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_objectcourse.ac_objectCourse_parentInRelation
     *
     * @return the value of ac_objectcourse.ac_objectCourse_parentInRelation
     *
     * @mbggenerated
     */
    public String getAcObjectcourseParentinrelation() {
        return acObjectcourseParentinrelation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_objectcourse.ac_objectCourse_parentInRelation
     *
     * @param acObjectcourseParentinrelation the value for ac_objectcourse.ac_objectCourse_parentInRelation
     *
     * @mbggenerated
     */
    public void setAcObjectcourseParentinrelation(String acObjectcourseParentinrelation) {
        this.acObjectcourseParentinrelation = acObjectcourseParentinrelation == null ? null : acObjectcourseParentinrelation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_objectcourse
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ac_objectCourse other = (ac_objectCourse) that;
        return (this.getAcObjectcourseId() == null ? other.getAcObjectcourseId() == null : this.getAcObjectcourseId().equals(other.getAcObjectcourseId()))
            && (this.getAcObjectcourseName() == null ? other.getAcObjectcourseName() == null : this.getAcObjectcourseName().equals(other.getAcObjectcourseName()))
            && (this.getAcObjectcourseContext() == null ? other.getAcObjectcourseContext() == null : this.getAcObjectcourseContext().equals(other.getAcObjectcourseContext()))
            && (this.getAcObjectcourseAddtime() == null ? other.getAcObjectcourseAddtime() == null : this.getAcObjectcourseAddtime().equals(other.getAcObjectcourseAddtime()))
            && (this.getAcObjectcourseParentinrelation() == null ? other.getAcObjectcourseParentinrelation() == null : this.getAcObjectcourseParentinrelation().equals(other.getAcObjectcourseParentinrelation()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_objectcourse
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getAcObjectcourseId() == null) ? 0 : getAcObjectcourseId().hashCode());
        result = prime * result + ((getAcObjectcourseName() == null) ? 0 : getAcObjectcourseName().hashCode());
        result = prime * result + ((getAcObjectcourseContext() == null) ? 0 : getAcObjectcourseContext().hashCode());
        result = prime * result + ((getAcObjectcourseAddtime() == null) ? 0 : getAcObjectcourseAddtime().hashCode());
        result = prime * result + ((getAcObjectcourseParentinrelation() == null) ? 0 : getAcObjectcourseParentinrelation().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_objectcourse
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", acObjectcourseId=").append(acObjectcourseId);
        sb.append(", acObjectcourseName=").append(acObjectcourseName);
        sb.append(", acObjectcourseContext=").append(acObjectcourseContext);
        sb.append(", acObjectcourseAddtime=").append(acObjectcourseAddtime);
        sb.append(", acObjectcourseParentinrelation=").append(acObjectcourseParentinrelation);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}