package com.artclub.model;

import java.io.Serializable;

public class ac_resume implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_resume.ac_resume_id
     *
     * @mbggenerated
     */
    private Integer acResumeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_resume.ac_resume_name
     *
     * @mbggenerated
     */
    private String acResumeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_resume.ac_resume_realId
     *
     * @mbggenerated
     */
    private String acResumeRealid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_resume.ac_resume_context
     *
     * @mbggenerated
     */
    private String acResumeContext;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_resume.ac_resume_contextUrl
     *
     * @mbggenerated
     */
    private String acResumeContexturl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_resume.ac_resume_video
     *
     * @mbggenerated
     */
    private String acResumeVideo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_resume.ac_resume_status
     *
     * @mbggenerated
     */
    private Integer acResumeStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ac_resume
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_resume.ac_resume_id
     *
     * @return the value of ac_resume.ac_resume_id
     *
     * @mbggenerated
     */
    public Integer getAcResumeId() {
        return acResumeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_resume.ac_resume_id
     *
     * @param acResumeId the value for ac_resume.ac_resume_id
     *
     * @mbggenerated
     */
    public void setAcResumeId(Integer acResumeId) {
        this.acResumeId = acResumeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_resume.ac_resume_name
     *
     * @return the value of ac_resume.ac_resume_name
     *
     * @mbggenerated
     */
    public String getAcResumeName() {
        return acResumeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_resume.ac_resume_name
     *
     * @param acResumeName the value for ac_resume.ac_resume_name
     *
     * @mbggenerated
     */
    public void setAcResumeName(String acResumeName) {
        this.acResumeName = acResumeName == null ? null : acResumeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_resume.ac_resume_realId
     *
     * @return the value of ac_resume.ac_resume_realId
     *
     * @mbggenerated
     */
    public String getAcResumeRealid() {
        return acResumeRealid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_resume.ac_resume_realId
     *
     * @param acResumeRealid the value for ac_resume.ac_resume_realId
     *
     * @mbggenerated
     */
    public void setAcResumeRealid(String acResumeRealid) {
        this.acResumeRealid = acResumeRealid == null ? null : acResumeRealid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_resume.ac_resume_context
     *
     * @return the value of ac_resume.ac_resume_context
     *
     * @mbggenerated
     */
    public String getAcResumeContext() {
        return acResumeContext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_resume.ac_resume_context
     *
     * @param acResumeContext the value for ac_resume.ac_resume_context
     *
     * @mbggenerated
     */
    public void setAcResumeContext(String acResumeContext) {
        this.acResumeContext = acResumeContext == null ? null : acResumeContext.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_resume.ac_resume_contextUrl
     *
     * @return the value of ac_resume.ac_resume_contextUrl
     *
     * @mbggenerated
     */
    public String getAcResumeContexturl() {
        return acResumeContexturl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_resume.ac_resume_contextUrl
     *
     * @param acResumeContexturl the value for ac_resume.ac_resume_contextUrl
     *
     * @mbggenerated
     */
    public void setAcResumeContexturl(String acResumeContexturl) {
        this.acResumeContexturl = acResumeContexturl == null ? null : acResumeContexturl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_resume.ac_resume_video
     *
     * @return the value of ac_resume.ac_resume_video
     *
     * @mbggenerated
     */
    public String getAcResumeVideo() {
        return acResumeVideo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_resume.ac_resume_video
     *
     * @param acResumeVideo the value for ac_resume.ac_resume_video
     *
     * @mbggenerated
     */
    public void setAcResumeVideo(String acResumeVideo) {
        this.acResumeVideo = acResumeVideo == null ? null : acResumeVideo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_resume.ac_resume_status
     *
     * @return the value of ac_resume.ac_resume_status
     *
     * @mbggenerated
     */
    public Integer getAcResumeStatus() {
        return acResumeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_resume.ac_resume_status
     *
     * @param acResumeStatus the value for ac_resume.ac_resume_status
     *
     * @mbggenerated
     */
    public void setAcResumeStatus(Integer acResumeStatus) {
        this.acResumeStatus = acResumeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_resume
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ac_resume other = (ac_resume) that;
        return (this.getAcResumeId() == null ? other.getAcResumeId() == null : this.getAcResumeId().equals(other.getAcResumeId()))
            && (this.getAcResumeName() == null ? other.getAcResumeName() == null : this.getAcResumeName().equals(other.getAcResumeName()))
            && (this.getAcResumeRealid() == null ? other.getAcResumeRealid() == null : this.getAcResumeRealid().equals(other.getAcResumeRealid()))
            && (this.getAcResumeContext() == null ? other.getAcResumeContext() == null : this.getAcResumeContext().equals(other.getAcResumeContext()))
            && (this.getAcResumeContexturl() == null ? other.getAcResumeContexturl() == null : this.getAcResumeContexturl().equals(other.getAcResumeContexturl()))
            && (this.getAcResumeVideo() == null ? other.getAcResumeVideo() == null : this.getAcResumeVideo().equals(other.getAcResumeVideo()))
            && (this.getAcResumeStatus() == null ? other.getAcResumeStatus() == null : this.getAcResumeStatus().equals(other.getAcResumeStatus()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_resume
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getAcResumeId() == null) ? 0 : getAcResumeId().hashCode());
        result = prime * result + ((getAcResumeName() == null) ? 0 : getAcResumeName().hashCode());
        result = prime * result + ((getAcResumeRealid() == null) ? 0 : getAcResumeRealid().hashCode());
        result = prime * result + ((getAcResumeContext() == null) ? 0 : getAcResumeContext().hashCode());
        result = prime * result + ((getAcResumeContexturl() == null) ? 0 : getAcResumeContexturl().hashCode());
        result = prime * result + ((getAcResumeVideo() == null) ? 0 : getAcResumeVideo().hashCode());
        result = prime * result + ((getAcResumeStatus() == null) ? 0 : getAcResumeStatus().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_resume
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", acResumeId=").append(acResumeId);
        sb.append(", acResumeName=").append(acResumeName);
        sb.append(", acResumeRealid=").append(acResumeRealid);
        sb.append(", acResumeContext=").append(acResumeContext);
        sb.append(", acResumeContexturl=").append(acResumeContexturl);
        sb.append(", acResumeVideo=").append(acResumeVideo);
        sb.append(", acResumeStatus=").append(acResumeStatus);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}