package com.artclub.model;

import java.io.Serializable;

public class ac_relationships implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_relationships.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_relationships.ac_relationships_parendId
     *
     * @mbggenerated
     */
    private Integer acRelationshipsParendid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_relationships.ac_relationships_level
     *
     * @mbggenerated
     */
    private Integer acRelationshipsLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_relationships.ac_reliationship_status
     *
     * @mbggenerated
     */
    private Integer acReliationshipStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_relationships.ac_relationship_addtime
     *
     * @mbggenerated
     */
    private Integer acRelationshipAddtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_relationships.ac_relationships_itemName
     *
     * @mbggenerated
     */
    private String acRelationshipsItemname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_relationships.ac_relationships_ItemId
     *
     * @mbggenerated
     */
    private String acRelationshipsItemid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ac_relationships
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_relationships.id
     *
     * @return the value of ac_relationships.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_relationships.id
     *
     * @param id the value for ac_relationships.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_relationships.ac_relationships_parendId
     *
     * @return the value of ac_relationships.ac_relationships_parendId
     *
     * @mbggenerated
     */
    public Integer getAcRelationshipsParendid() {
        return acRelationshipsParendid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_relationships.ac_relationships_parendId
     *
     * @param acRelationshipsParendid the value for ac_relationships.ac_relationships_parendId
     *
     * @mbggenerated
     */
    public void setAcRelationshipsParendid(Integer acRelationshipsParendid) {
        this.acRelationshipsParendid = acRelationshipsParendid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_relationships.ac_relationships_level
     *
     * @return the value of ac_relationships.ac_relationships_level
     *
     * @mbggenerated
     */
    public Integer getAcRelationshipsLevel() {
        return acRelationshipsLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_relationships.ac_relationships_level
     *
     * @param acRelationshipsLevel the value for ac_relationships.ac_relationships_level
     *
     * @mbggenerated
     */
    public void setAcRelationshipsLevel(Integer acRelationshipsLevel) {
        this.acRelationshipsLevel = acRelationshipsLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_relationships.ac_reliationship_status
     *
     * @return the value of ac_relationships.ac_reliationship_status
     *
     * @mbggenerated
     */
    public Integer getAcReliationshipStatus() {
        return acReliationshipStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_relationships.ac_reliationship_status
     *
     * @param acReliationshipStatus the value for ac_relationships.ac_reliationship_status
     *
     * @mbggenerated
     */
    public void setAcReliationshipStatus(Integer acReliationshipStatus) {
        this.acReliationshipStatus = acReliationshipStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_relationships.ac_relationship_addtime
     *
     * @return the value of ac_relationships.ac_relationship_addtime
     *
     * @mbggenerated
     */
    public Integer getAcRelationshipAddtime() {
        return acRelationshipAddtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_relationships.ac_relationship_addtime
     *
     * @param acRelationshipAddtime the value for ac_relationships.ac_relationship_addtime
     *
     * @mbggenerated
     */
    public void setAcRelationshipAddtime(Integer acRelationshipAddtime) {
        this.acRelationshipAddtime = acRelationshipAddtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_relationships.ac_relationships_itemName
     *
     * @return the value of ac_relationships.ac_relationships_itemName
     *
     * @mbggenerated
     */
    public String getAcRelationshipsItemname() {
        return acRelationshipsItemname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_relationships.ac_relationships_itemName
     *
     * @param acRelationshipsItemname the value for ac_relationships.ac_relationships_itemName
     *
     * @mbggenerated
     */
    public void setAcRelationshipsItemname(String acRelationshipsItemname) {
        this.acRelationshipsItemname = acRelationshipsItemname == null ? null : acRelationshipsItemname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_relationships.ac_relationships_ItemId
     *
     * @return the value of ac_relationships.ac_relationships_ItemId
     *
     * @mbggenerated
     */
    public String getAcRelationshipsItemid() {
        return acRelationshipsItemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_relationships.ac_relationships_ItemId
     *
     * @param acRelationshipsItemid the value for ac_relationships.ac_relationships_ItemId
     *
     * @mbggenerated
     */
    public void setAcRelationshipsItemid(String acRelationshipsItemid) {
        this.acRelationshipsItemid = acRelationshipsItemid == null ? null : acRelationshipsItemid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_relationships
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ac_relationships other = (ac_relationships) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getAcRelationshipsParendid() == null ? other.getAcRelationshipsParendid() == null : this.getAcRelationshipsParendid().equals(other.getAcRelationshipsParendid()))
            && (this.getAcRelationshipsLevel() == null ? other.getAcRelationshipsLevel() == null : this.getAcRelationshipsLevel().equals(other.getAcRelationshipsLevel()))
            && (this.getAcReliationshipStatus() == null ? other.getAcReliationshipStatus() == null : this.getAcReliationshipStatus().equals(other.getAcReliationshipStatus()))
            && (this.getAcRelationshipAddtime() == null ? other.getAcRelationshipAddtime() == null : this.getAcRelationshipAddtime().equals(other.getAcRelationshipAddtime()))
            && (this.getAcRelationshipsItemname() == null ? other.getAcRelationshipsItemname() == null : this.getAcRelationshipsItemname().equals(other.getAcRelationshipsItemname()))
            && (this.getAcRelationshipsItemid() == null ? other.getAcRelationshipsItemid() == null : this.getAcRelationshipsItemid().equals(other.getAcRelationshipsItemid()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_relationships
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getAcRelationshipsParendid() == null) ? 0 : getAcRelationshipsParendid().hashCode());
        result = prime * result + ((getAcRelationshipsLevel() == null) ? 0 : getAcRelationshipsLevel().hashCode());
        result = prime * result + ((getAcReliationshipStatus() == null) ? 0 : getAcReliationshipStatus().hashCode());
        result = prime * result + ((getAcRelationshipAddtime() == null) ? 0 : getAcRelationshipAddtime().hashCode());
        result = prime * result + ((getAcRelationshipsItemname() == null) ? 0 : getAcRelationshipsItemname().hashCode());
        result = prime * result + ((getAcRelationshipsItemid() == null) ? 0 : getAcRelationshipsItemid().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_relationships
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", acRelationshipsParendid=").append(acRelationshipsParendid);
        sb.append(", acRelationshipsLevel=").append(acRelationshipsLevel);
        sb.append(", acReliationshipStatus=").append(acReliationshipStatus);
        sb.append(", acRelationshipAddtime=").append(acRelationshipAddtime);
        sb.append(", acRelationshipsItemname=").append(acRelationshipsItemname);
        sb.append(", acRelationshipsItemid=").append(acRelationshipsItemid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}