package com.artclub.model;

import java.io.Serializable;

public class ac_student_course implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_student_course.ac_student_course_id
     *
     * @mbggenerated
     */
    private Integer acStudentCourseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_student_course.ac_student_course_stuId
     *
     * @mbggenerated
     */
    private Integer acStudentCourseStuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_student_course.ac_student_course_courseId
     *
     * @mbggenerated
     */
    private Integer acStudentCourseCourseid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_student_course.ac_student_course_pickTime
     *
     * @mbggenerated
     */
    private String acStudentCoursePicktime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_student_course.ac_student_course_score
     *
     * @mbggenerated
     */
    private String acStudentCourseScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ac_student_course
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_student_course.ac_student_course_id
     *
     * @return the value of ac_student_course.ac_student_course_id
     *
     * @mbggenerated
     */
    public Integer getAcStudentCourseId() {
        return acStudentCourseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_student_course.ac_student_course_id
     *
     * @param acStudentCourseId the value for ac_student_course.ac_student_course_id
     *
     * @mbggenerated
     */
    public void setAcStudentCourseId(Integer acStudentCourseId) {
        this.acStudentCourseId = acStudentCourseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_student_course.ac_student_course_stuId
     *
     * @return the value of ac_student_course.ac_student_course_stuId
     *
     * @mbggenerated
     */
    public Integer getAcStudentCourseStuid() {
        return acStudentCourseStuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_student_course.ac_student_course_stuId
     *
     * @param acStudentCourseStuid the value for ac_student_course.ac_student_course_stuId
     *
     * @mbggenerated
     */
    public void setAcStudentCourseStuid(Integer acStudentCourseStuid) {
        this.acStudentCourseStuid = acStudentCourseStuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_student_course.ac_student_course_courseId
     *
     * @return the value of ac_student_course.ac_student_course_courseId
     *
     * @mbggenerated
     */
    public Integer getAcStudentCourseCourseid() {
        return acStudentCourseCourseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_student_course.ac_student_course_courseId
     *
     * @param acStudentCourseCourseid the value for ac_student_course.ac_student_course_courseId
     *
     * @mbggenerated
     */
    public void setAcStudentCourseCourseid(Integer acStudentCourseCourseid) {
        this.acStudentCourseCourseid = acStudentCourseCourseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_student_course.ac_student_course_pickTime
     *
     * @return the value of ac_student_course.ac_student_course_pickTime
     *
     * @mbggenerated
     */
    public String getAcStudentCoursePicktime() {
        return acStudentCoursePicktime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_student_course.ac_student_course_pickTime
     *
     * @param acStudentCoursePicktime the value for ac_student_course.ac_student_course_pickTime
     *
     * @mbggenerated
     */
    public void setAcStudentCoursePicktime(String acStudentCoursePicktime) {
        this.acStudentCoursePicktime = acStudentCoursePicktime == null ? null : acStudentCoursePicktime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_student_course.ac_student_course_score
     *
     * @return the value of ac_student_course.ac_student_course_score
     *
     * @mbggenerated
     */
    public String getAcStudentCourseScore() {
        return acStudentCourseScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_student_course.ac_student_course_score
     *
     * @param acStudentCourseScore the value for ac_student_course.ac_student_course_score
     *
     * @mbggenerated
     */
    public void setAcStudentCourseScore(String acStudentCourseScore) {
        this.acStudentCourseScore = acStudentCourseScore == null ? null : acStudentCourseScore.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_student_course
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ac_student_course other = (ac_student_course) that;
        return (this.getAcStudentCourseId() == null ? other.getAcStudentCourseId() == null : this.getAcStudentCourseId().equals(other.getAcStudentCourseId()))
            && (this.getAcStudentCourseStuid() == null ? other.getAcStudentCourseStuid() == null : this.getAcStudentCourseStuid().equals(other.getAcStudentCourseStuid()))
            && (this.getAcStudentCourseCourseid() == null ? other.getAcStudentCourseCourseid() == null : this.getAcStudentCourseCourseid().equals(other.getAcStudentCourseCourseid()))
            && (this.getAcStudentCoursePicktime() == null ? other.getAcStudentCoursePicktime() == null : this.getAcStudentCoursePicktime().equals(other.getAcStudentCoursePicktime()))
            && (this.getAcStudentCourseScore() == null ? other.getAcStudentCourseScore() == null : this.getAcStudentCourseScore().equals(other.getAcStudentCourseScore()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_student_course
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getAcStudentCourseId() == null) ? 0 : getAcStudentCourseId().hashCode());
        result = prime * result + ((getAcStudentCourseStuid() == null) ? 0 : getAcStudentCourseStuid().hashCode());
        result = prime * result + ((getAcStudentCourseCourseid() == null) ? 0 : getAcStudentCourseCourseid().hashCode());
        result = prime * result + ((getAcStudentCoursePicktime() == null) ? 0 : getAcStudentCoursePicktime().hashCode());
        result = prime * result + ((getAcStudentCourseScore() == null) ? 0 : getAcStudentCourseScore().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_student_course
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", acStudentCourseId=").append(acStudentCourseId);
        sb.append(", acStudentCourseStuid=").append(acStudentCourseStuid);
        sb.append(", acStudentCourseCourseid=").append(acStudentCourseCourseid);
        sb.append(", acStudentCoursePicktime=").append(acStudentCoursePicktime);
        sb.append(", acStudentCourseScore=").append(acStudentCourseScore);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}