package com.artclub.model;

import java.io.Serializable;

public class ac_studentvideo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_studentvideo.ac_studentVideo_id
     *
     * @mbggenerated
     */
    private Integer acStudentvideoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_studentvideo.ac_studentVideo_url
     *
     * @mbggenerated
     */
    private String acStudentvideoUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_studentvideo.ac_studentVideo_studentName
     *
     * @mbggenerated
     */
    private String acStudentvideoStudentname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_studentvideo.ac_studentVideo_time
     *
     * @mbggenerated
     */
    private String acStudentvideoTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_studentvideo.ac_studentVideo_status
     *
     * @mbggenerated
     */
    private Integer acStudentvideoStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_studentvideo.ac_studentVideo_stuId
     *
     * @mbggenerated
     */
    private Integer acStudentvideoStuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_studentvideo.ac_studentVideo_likes
     *
     * @mbggenerated
     */
    private String acStudentvideoLikes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_studentvideo.ac_studentVideo_context
     *
     * @mbggenerated
     */
    private String acStudentvideoContext;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_studentvideo.ac_studentVideo_summary
     *
     * @mbggenerated
     */
    private String acStudentvideoSummary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ac_studentvideo
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_studentvideo.ac_studentVideo_id
     *
     * @return the value of ac_studentvideo.ac_studentVideo_id
     *
     * @mbggenerated
     */
    public Integer getAcStudentvideoId() {
        return acStudentvideoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_studentvideo.ac_studentVideo_id
     *
     * @param acStudentvideoId the value for ac_studentvideo.ac_studentVideo_id
     *
     * @mbggenerated
     */
    public void setAcStudentvideoId(Integer acStudentvideoId) {
        this.acStudentvideoId = acStudentvideoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_studentvideo.ac_studentVideo_url
     *
     * @return the value of ac_studentvideo.ac_studentVideo_url
     *
     * @mbggenerated
     */
    public String getAcStudentvideoUrl() {
        return acStudentvideoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_studentvideo.ac_studentVideo_url
     *
     * @param acStudentvideoUrl the value for ac_studentvideo.ac_studentVideo_url
     *
     * @mbggenerated
     */
    public void setAcStudentvideoUrl(String acStudentvideoUrl) {
        this.acStudentvideoUrl = acStudentvideoUrl == null ? null : acStudentvideoUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_studentvideo.ac_studentVideo_studentName
     *
     * @return the value of ac_studentvideo.ac_studentVideo_studentName
     *
     * @mbggenerated
     */
    public String getAcStudentvideoStudentname() {
        return acStudentvideoStudentname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_studentvideo.ac_studentVideo_studentName
     *
     * @param acStudentvideoStudentname the value for ac_studentvideo.ac_studentVideo_studentName
     *
     * @mbggenerated
     */
    public void setAcStudentvideoStudentname(String acStudentvideoStudentname) {
        this.acStudentvideoStudentname = acStudentvideoStudentname == null ? null : acStudentvideoStudentname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_studentvideo.ac_studentVideo_time
     *
     * @return the value of ac_studentvideo.ac_studentVideo_time
     *
     * @mbggenerated
     */
    public String getAcStudentvideoTime() {
        return acStudentvideoTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_studentvideo.ac_studentVideo_time
     *
     * @param acStudentvideoTime the value for ac_studentvideo.ac_studentVideo_time
     *
     * @mbggenerated
     */
    public void setAcStudentvideoTime(String acStudentvideoTime) {
        this.acStudentvideoTime = acStudentvideoTime == null ? null : acStudentvideoTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_studentvideo.ac_studentVideo_status
     *
     * @return the value of ac_studentvideo.ac_studentVideo_status
     *
     * @mbggenerated
     */
    public Integer getAcStudentvideoStatus() {
        return acStudentvideoStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_studentvideo.ac_studentVideo_status
     *
     * @param acStudentvideoStatus the value for ac_studentvideo.ac_studentVideo_status
     *
     * @mbggenerated
     */
    public void setAcStudentvideoStatus(Integer acStudentvideoStatus) {
        this.acStudentvideoStatus = acStudentvideoStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_studentvideo.ac_studentVideo_stuId
     *
     * @return the value of ac_studentvideo.ac_studentVideo_stuId
     *
     * @mbggenerated
     */
    public Integer getAcStudentvideoStuid() {
        return acStudentvideoStuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_studentvideo.ac_studentVideo_stuId
     *
     * @param acStudentvideoStuid the value for ac_studentvideo.ac_studentVideo_stuId
     *
     * @mbggenerated
     */
    public void setAcStudentvideoStuid(Integer acStudentvideoStuid) {
        this.acStudentvideoStuid = acStudentvideoStuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_studentvideo.ac_studentVideo_likes
     *
     * @return the value of ac_studentvideo.ac_studentVideo_likes
     *
     * @mbggenerated
     */
    public String getAcStudentvideoLikes() {
        return acStudentvideoLikes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_studentvideo.ac_studentVideo_likes
     *
     * @param acStudentvideoLikes the value for ac_studentvideo.ac_studentVideo_likes
     *
     * @mbggenerated
     */
    public void setAcStudentvideoLikes(String acStudentvideoLikes) {
        this.acStudentvideoLikes = acStudentvideoLikes == null ? null : acStudentvideoLikes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_studentvideo.ac_studentVideo_context
     *
     * @return the value of ac_studentvideo.ac_studentVideo_context
     *
     * @mbggenerated
     */
    public String getAcStudentvideoContext() {
        return acStudentvideoContext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_studentvideo.ac_studentVideo_context
     *
     * @param acStudentvideoContext the value for ac_studentvideo.ac_studentVideo_context
     *
     * @mbggenerated
     */
    public void setAcStudentvideoContext(String acStudentvideoContext) {
        this.acStudentvideoContext = acStudentvideoContext == null ? null : acStudentvideoContext.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_studentvideo.ac_studentVideo_summary
     *
     * @return the value of ac_studentvideo.ac_studentVideo_summary
     *
     * @mbggenerated
     */
    public String getAcStudentvideoSummary() {
        return acStudentvideoSummary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_studentvideo.ac_studentVideo_summary
     *
     * @param acStudentvideoSummary the value for ac_studentvideo.ac_studentVideo_summary
     *
     * @mbggenerated
     */
    public void setAcStudentvideoSummary(String acStudentvideoSummary) {
        this.acStudentvideoSummary = acStudentvideoSummary == null ? null : acStudentvideoSummary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_studentvideo
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ac_studentvideo other = (ac_studentvideo) that;
        return (this.getAcStudentvideoId() == null ? other.getAcStudentvideoId() == null : this.getAcStudentvideoId().equals(other.getAcStudentvideoId()))
            && (this.getAcStudentvideoUrl() == null ? other.getAcStudentvideoUrl() == null : this.getAcStudentvideoUrl().equals(other.getAcStudentvideoUrl()))
            && (this.getAcStudentvideoStudentname() == null ? other.getAcStudentvideoStudentname() == null : this.getAcStudentvideoStudentname().equals(other.getAcStudentvideoStudentname()))
            && (this.getAcStudentvideoTime() == null ? other.getAcStudentvideoTime() == null : this.getAcStudentvideoTime().equals(other.getAcStudentvideoTime()))
            && (this.getAcStudentvideoStatus() == null ? other.getAcStudentvideoStatus() == null : this.getAcStudentvideoStatus().equals(other.getAcStudentvideoStatus()))
            && (this.getAcStudentvideoStuid() == null ? other.getAcStudentvideoStuid() == null : this.getAcStudentvideoStuid().equals(other.getAcStudentvideoStuid()))
            && (this.getAcStudentvideoLikes() == null ? other.getAcStudentvideoLikes() == null : this.getAcStudentvideoLikes().equals(other.getAcStudentvideoLikes()))
            && (this.getAcStudentvideoContext() == null ? other.getAcStudentvideoContext() == null : this.getAcStudentvideoContext().equals(other.getAcStudentvideoContext()))
            && (this.getAcStudentvideoSummary() == null ? other.getAcStudentvideoSummary() == null : this.getAcStudentvideoSummary().equals(other.getAcStudentvideoSummary()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_studentvideo
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getAcStudentvideoId() == null) ? 0 : getAcStudentvideoId().hashCode());
        result = prime * result + ((getAcStudentvideoUrl() == null) ? 0 : getAcStudentvideoUrl().hashCode());
        result = prime * result + ((getAcStudentvideoStudentname() == null) ? 0 : getAcStudentvideoStudentname().hashCode());
        result = prime * result + ((getAcStudentvideoTime() == null) ? 0 : getAcStudentvideoTime().hashCode());
        result = prime * result + ((getAcStudentvideoStatus() == null) ? 0 : getAcStudentvideoStatus().hashCode());
        result = prime * result + ((getAcStudentvideoStuid() == null) ? 0 : getAcStudentvideoStuid().hashCode());
        result = prime * result + ((getAcStudentvideoLikes() == null) ? 0 : getAcStudentvideoLikes().hashCode());
        result = prime * result + ((getAcStudentvideoContext() == null) ? 0 : getAcStudentvideoContext().hashCode());
        result = prime * result + ((getAcStudentvideoSummary() == null) ? 0 : getAcStudentvideoSummary().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_studentvideo
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", acStudentvideoId=").append(acStudentvideoId);
        sb.append(", acStudentvideoUrl=").append(acStudentvideoUrl);
        sb.append(", acStudentvideoStudentname=").append(acStudentvideoStudentname);
        sb.append(", acStudentvideoTime=").append(acStudentvideoTime);
        sb.append(", acStudentvideoStatus=").append(acStudentvideoStatus);
        sb.append(", acStudentvideoStuid=").append(acStudentvideoStuid);
        sb.append(", acStudentvideoLikes=").append(acStudentvideoLikes);
        sb.append(", acStudentvideoContext=").append(acStudentvideoContext);
        sb.append(", acStudentvideoSummary=").append(acStudentvideoSummary);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}