package com.artclub.model;

import java.io.Serializable;

public class ac_teacher_course implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_teacher_course.ac_teacher_course_id
     *
     * @mbggenerated
     */
    private Integer acTeacherCourseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_teacher_course.ac_teacher_course_teacherId
     *
     * @mbggenerated
     */
    private Integer acTeacherCourseTeacherid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_teacher_course.ac_teacher_course_courseId
     *
     * @mbggenerated
     */
    private Integer acTeacherCourseCourseid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_teacher_course.ac_teacher_course_time
     *
     * @mbggenerated
     */
    private String acTeacherCourseTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ac_teacher_course
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_teacher_course.ac_teacher_course_id
     *
     * @return the value of ac_teacher_course.ac_teacher_course_id
     *
     * @mbggenerated
     */
    public Integer getAcTeacherCourseId() {
        return acTeacherCourseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_teacher_course.ac_teacher_course_id
     *
     * @param acTeacherCourseId the value for ac_teacher_course.ac_teacher_course_id
     *
     * @mbggenerated
     */
    public void setAcTeacherCourseId(Integer acTeacherCourseId) {
        this.acTeacherCourseId = acTeacherCourseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_teacher_course.ac_teacher_course_teacherId
     *
     * @return the value of ac_teacher_course.ac_teacher_course_teacherId
     *
     * @mbggenerated
     */
    public Integer getAcTeacherCourseTeacherid() {
        return acTeacherCourseTeacherid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_teacher_course.ac_teacher_course_teacherId
     *
     * @param acTeacherCourseTeacherid the value for ac_teacher_course.ac_teacher_course_teacherId
     *
     * @mbggenerated
     */
    public void setAcTeacherCourseTeacherid(Integer acTeacherCourseTeacherid) {
        this.acTeacherCourseTeacherid = acTeacherCourseTeacherid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_teacher_course.ac_teacher_course_courseId
     *
     * @return the value of ac_teacher_course.ac_teacher_course_courseId
     *
     * @mbggenerated
     */
    public Integer getAcTeacherCourseCourseid() {
        return acTeacherCourseCourseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_teacher_course.ac_teacher_course_courseId
     *
     * @param acTeacherCourseCourseid the value for ac_teacher_course.ac_teacher_course_courseId
     *
     * @mbggenerated
     */
    public void setAcTeacherCourseCourseid(Integer acTeacherCourseCourseid) {
        this.acTeacherCourseCourseid = acTeacherCourseCourseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_teacher_course.ac_teacher_course_time
     *
     * @return the value of ac_teacher_course.ac_teacher_course_time
     *
     * @mbggenerated
     */
    public String getAcTeacherCourseTime() {
        return acTeacherCourseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_teacher_course.ac_teacher_course_time
     *
     * @param acTeacherCourseTime the value for ac_teacher_course.ac_teacher_course_time
     *
     * @mbggenerated
     */
    public void setAcTeacherCourseTime(String acTeacherCourseTime) {
        this.acTeacherCourseTime = acTeacherCourseTime == null ? null : acTeacherCourseTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_teacher_course
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ac_teacher_course other = (ac_teacher_course) that;
        return (this.getAcTeacherCourseId() == null ? other.getAcTeacherCourseId() == null : this.getAcTeacherCourseId().equals(other.getAcTeacherCourseId()))
            && (this.getAcTeacherCourseTeacherid() == null ? other.getAcTeacherCourseTeacherid() == null : this.getAcTeacherCourseTeacherid().equals(other.getAcTeacherCourseTeacherid()))
            && (this.getAcTeacherCourseCourseid() == null ? other.getAcTeacherCourseCourseid() == null : this.getAcTeacherCourseCourseid().equals(other.getAcTeacherCourseCourseid()))
            && (this.getAcTeacherCourseTime() == null ? other.getAcTeacherCourseTime() == null : this.getAcTeacherCourseTime().equals(other.getAcTeacherCourseTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_teacher_course
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getAcTeacherCourseId() == null) ? 0 : getAcTeacherCourseId().hashCode());
        result = prime * result + ((getAcTeacherCourseTeacherid() == null) ? 0 : getAcTeacherCourseTeacherid().hashCode());
        result = prime * result + ((getAcTeacherCourseCourseid() == null) ? 0 : getAcTeacherCourseCourseid().hashCode());
        result = prime * result + ((getAcTeacherCourseTime() == null) ? 0 : getAcTeacherCourseTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_teacher_course
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", acTeacherCourseId=").append(acTeacherCourseId);
        sb.append(", acTeacherCourseTeacherid=").append(acTeacherCourseTeacherid);
        sb.append(", acTeacherCourseCourseid=").append(acTeacherCourseCourseid);
        sb.append(", acTeacherCourseTime=").append(acTeacherCourseTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}