package com.artclub.model;

import java.io.Serializable;

public class ac_teacher implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_teacher.ac_teacher_id
     *
     * @mbggenerated
     */
    private Integer acTeacherId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_teacher.ac_teacher_userId
     *
     * @mbggenerated
     */
    private Integer acTeacherUserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_teacher.ac_teacher_phoneNumber
     *
     * @mbggenerated
     */
    private String acTeacherPhonenumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_teacher.ac_teacher_password
     *
     * @mbggenerated
     */
    private String acTeacherPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_teacher.ac_teacher_name
     *
     * @mbggenerated
     */
    private String acTeacherName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_teacher.ac_teacher_realId
     *
     * @mbggenerated
     */
    private String acTeacherRealid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_teacher.ac_teacher_bkPhoneNumber
     *
     * @mbggenerated
     */
    private String acTeacherBkphonenumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_teacher.ac_teacher_status
     *
     * @mbggenerated
     */
    private Integer acTeacherStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_teacher.ac_teacher_fromConpany
     *
     * @mbggenerated
     */
    private String acTeacherFromconpany;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_teacher.ac_teacher_proveFile
     *
     * @mbggenerated
     */
    private String acTeacherProvefile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_teacher.ac_teacher_proveFileChecked
     *
     * @mbggenerated
     */
    private String acTeacherProvefilechecked;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ac_teacher
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_teacher.ac_teacher_id
     *
     * @return the value of ac_teacher.ac_teacher_id
     *
     * @mbggenerated
     */
    public Integer getAcTeacherId() {
        return acTeacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_teacher.ac_teacher_id
     *
     * @param acTeacherId the value for ac_teacher.ac_teacher_id
     *
     * @mbggenerated
     */
    public void setAcTeacherId(Integer acTeacherId) {
        this.acTeacherId = acTeacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_teacher.ac_teacher_userId
     *
     * @return the value of ac_teacher.ac_teacher_userId
     *
     * @mbggenerated
     */
    public Integer getAcTeacherUserid() {
        return acTeacherUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_teacher.ac_teacher_userId
     *
     * @param acTeacherUserid the value for ac_teacher.ac_teacher_userId
     *
     * @mbggenerated
     */
    public void setAcTeacherUserid(Integer acTeacherUserid) {
        this.acTeacherUserid = acTeacherUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_teacher.ac_teacher_phoneNumber
     *
     * @return the value of ac_teacher.ac_teacher_phoneNumber
     *
     * @mbggenerated
     */
    public String getAcTeacherPhonenumber() {
        return acTeacherPhonenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_teacher.ac_teacher_phoneNumber
     *
     * @param acTeacherPhonenumber the value for ac_teacher.ac_teacher_phoneNumber
     *
     * @mbggenerated
     */
    public void setAcTeacherPhonenumber(String acTeacherPhonenumber) {
        this.acTeacherPhonenumber = acTeacherPhonenumber == null ? null : acTeacherPhonenumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_teacher.ac_teacher_password
     *
     * @return the value of ac_teacher.ac_teacher_password
     *
     * @mbggenerated
     */
    public String getAcTeacherPassword() {
        return acTeacherPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_teacher.ac_teacher_password
     *
     * @param acTeacherPassword the value for ac_teacher.ac_teacher_password
     *
     * @mbggenerated
     */
    public void setAcTeacherPassword(String acTeacherPassword) {
        this.acTeacherPassword = acTeacherPassword == null ? null : acTeacherPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_teacher.ac_teacher_name
     *
     * @return the value of ac_teacher.ac_teacher_name
     *
     * @mbggenerated
     */
    public String getAcTeacherName() {
        return acTeacherName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_teacher.ac_teacher_name
     *
     * @param acTeacherName the value for ac_teacher.ac_teacher_name
     *
     * @mbggenerated
     */
    public void setAcTeacherName(String acTeacherName) {
        this.acTeacherName = acTeacherName == null ? null : acTeacherName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_teacher.ac_teacher_realId
     *
     * @return the value of ac_teacher.ac_teacher_realId
     *
     * @mbggenerated
     */
    public String getAcTeacherRealid() {
        return acTeacherRealid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_teacher.ac_teacher_realId
     *
     * @param acTeacherRealid the value for ac_teacher.ac_teacher_realId
     *
     * @mbggenerated
     */
    public void setAcTeacherRealid(String acTeacherRealid) {
        this.acTeacherRealid = acTeacherRealid == null ? null : acTeacherRealid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_teacher.ac_teacher_bkPhoneNumber
     *
     * @return the value of ac_teacher.ac_teacher_bkPhoneNumber
     *
     * @mbggenerated
     */
    public String getAcTeacherBkphonenumber() {
        return acTeacherBkphonenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_teacher.ac_teacher_bkPhoneNumber
     *
     * @param acTeacherBkphonenumber the value for ac_teacher.ac_teacher_bkPhoneNumber
     *
     * @mbggenerated
     */
    public void setAcTeacherBkphonenumber(String acTeacherBkphonenumber) {
        this.acTeacherBkphonenumber = acTeacherBkphonenumber == null ? null : acTeacherBkphonenumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_teacher.ac_teacher_status
     *
     * @return the value of ac_teacher.ac_teacher_status
     *
     * @mbggenerated
     */
    public Integer getAcTeacherStatus() {
        return acTeacherStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_teacher.ac_teacher_status
     *
     * @param acTeacherStatus the value for ac_teacher.ac_teacher_status
     *
     * @mbggenerated
     */
    public void setAcTeacherStatus(Integer acTeacherStatus) {
        this.acTeacherStatus = acTeacherStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_teacher.ac_teacher_fromConpany
     *
     * @return the value of ac_teacher.ac_teacher_fromConpany
     *
     * @mbggenerated
     */
    public String getAcTeacherFromconpany() {
        return acTeacherFromconpany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_teacher.ac_teacher_fromConpany
     *
     * @param acTeacherFromconpany the value for ac_teacher.ac_teacher_fromConpany
     *
     * @mbggenerated
     */
    public void setAcTeacherFromconpany(String acTeacherFromconpany) {
        this.acTeacherFromconpany = acTeacherFromconpany == null ? null : acTeacherFromconpany.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_teacher.ac_teacher_proveFile
     *
     * @return the value of ac_teacher.ac_teacher_proveFile
     *
     * @mbggenerated
     */
    public String getAcTeacherProvefile() {
        return acTeacherProvefile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_teacher.ac_teacher_proveFile
     *
     * @param acTeacherProvefile the value for ac_teacher.ac_teacher_proveFile
     *
     * @mbggenerated
     */
    public void setAcTeacherProvefile(String acTeacherProvefile) {
        this.acTeacherProvefile = acTeacherProvefile == null ? null : acTeacherProvefile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_teacher.ac_teacher_proveFileChecked
     *
     * @return the value of ac_teacher.ac_teacher_proveFileChecked
     *
     * @mbggenerated
     */
    public String getAcTeacherProvefilechecked() {
        return acTeacherProvefilechecked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_teacher.ac_teacher_proveFileChecked
     *
     * @param acTeacherProvefilechecked the value for ac_teacher.ac_teacher_proveFileChecked
     *
     * @mbggenerated
     */
    public void setAcTeacherProvefilechecked(String acTeacherProvefilechecked) {
        this.acTeacherProvefilechecked = acTeacherProvefilechecked == null ? null : acTeacherProvefilechecked.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_teacher
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ac_teacher other = (ac_teacher) that;
        return (this.getAcTeacherId() == null ? other.getAcTeacherId() == null : this.getAcTeacherId().equals(other.getAcTeacherId()))
            && (this.getAcTeacherUserid() == null ? other.getAcTeacherUserid() == null : this.getAcTeacherUserid().equals(other.getAcTeacherUserid()))
            && (this.getAcTeacherPhonenumber() == null ? other.getAcTeacherPhonenumber() == null : this.getAcTeacherPhonenumber().equals(other.getAcTeacherPhonenumber()))
            && (this.getAcTeacherPassword() == null ? other.getAcTeacherPassword() == null : this.getAcTeacherPassword().equals(other.getAcTeacherPassword()))
            && (this.getAcTeacherName() == null ? other.getAcTeacherName() == null : this.getAcTeacherName().equals(other.getAcTeacherName()))
            && (this.getAcTeacherRealid() == null ? other.getAcTeacherRealid() == null : this.getAcTeacherRealid().equals(other.getAcTeacherRealid()))
            && (this.getAcTeacherBkphonenumber() == null ? other.getAcTeacherBkphonenumber() == null : this.getAcTeacherBkphonenumber().equals(other.getAcTeacherBkphonenumber()))
            && (this.getAcTeacherStatus() == null ? other.getAcTeacherStatus() == null : this.getAcTeacherStatus().equals(other.getAcTeacherStatus()))
            && (this.getAcTeacherFromconpany() == null ? other.getAcTeacherFromconpany() == null : this.getAcTeacherFromconpany().equals(other.getAcTeacherFromconpany()))
            && (this.getAcTeacherProvefile() == null ? other.getAcTeacherProvefile() == null : this.getAcTeacherProvefile().equals(other.getAcTeacherProvefile()))
            && (this.getAcTeacherProvefilechecked() == null ? other.getAcTeacherProvefilechecked() == null : this.getAcTeacherProvefilechecked().equals(other.getAcTeacherProvefilechecked()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_teacher
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getAcTeacherId() == null) ? 0 : getAcTeacherId().hashCode());
        result = prime * result + ((getAcTeacherUserid() == null) ? 0 : getAcTeacherUserid().hashCode());
        result = prime * result + ((getAcTeacherPhonenumber() == null) ? 0 : getAcTeacherPhonenumber().hashCode());
        result = prime * result + ((getAcTeacherPassword() == null) ? 0 : getAcTeacherPassword().hashCode());
        result = prime * result + ((getAcTeacherName() == null) ? 0 : getAcTeacherName().hashCode());
        result = prime * result + ((getAcTeacherRealid() == null) ? 0 : getAcTeacherRealid().hashCode());
        result = prime * result + ((getAcTeacherBkphonenumber() == null) ? 0 : getAcTeacherBkphonenumber().hashCode());
        result = prime * result + ((getAcTeacherStatus() == null) ? 0 : getAcTeacherStatus().hashCode());
        result = prime * result + ((getAcTeacherFromconpany() == null) ? 0 : getAcTeacherFromconpany().hashCode());
        result = prime * result + ((getAcTeacherProvefile() == null) ? 0 : getAcTeacherProvefile().hashCode());
        result = prime * result + ((getAcTeacherProvefilechecked() == null) ? 0 : getAcTeacherProvefilechecked().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_teacher
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", acTeacherId=").append(acTeacherId);
        sb.append(", acTeacherUserid=").append(acTeacherUserid);
        sb.append(", acTeacherPhonenumber=").append(acTeacherPhonenumber);
        sb.append(", acTeacherPassword=").append(acTeacherPassword);
        sb.append(", acTeacherName=").append(acTeacherName);
        sb.append(", acTeacherRealid=").append(acTeacherRealid);
        sb.append(", acTeacherBkphonenumber=").append(acTeacherBkphonenumber);
        sb.append(", acTeacherStatus=").append(acTeacherStatus);
        sb.append(", acTeacherFromconpany=").append(acTeacherFromconpany);
        sb.append(", acTeacherProvefile=").append(acTeacherProvefile);
        sb.append(", acTeacherProvefilechecked=").append(acTeacherProvefilechecked);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}