package com.artclub.model;

import java.io.Serializable;

public class ac_teacher_instrument implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_teacher_instrument.ac_teacher_instrument_id
     *
     * @mbggenerated
     */
    private Integer acTeacherInstrumentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_teacher_instrument.ac_teacher_instrument_teacherId
     *
     * @mbggenerated
     */
    private Integer acTeacherInstrumentTeacherid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_teacher_instrument.ac_teacher_instrument_instrumentId
     *
     * @mbggenerated
     */
    private Integer acTeacherInstrumentInstrumentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ac_teacher_instrument
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_teacher_instrument.ac_teacher_instrument_id
     *
     * @return the value of ac_teacher_instrument.ac_teacher_instrument_id
     *
     * @mbggenerated
     */
    public Integer getAcTeacherInstrumentId() {
        return acTeacherInstrumentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_teacher_instrument.ac_teacher_instrument_id
     *
     * @param acTeacherInstrumentId the value for ac_teacher_instrument.ac_teacher_instrument_id
     *
     * @mbggenerated
     */
    public void setAcTeacherInstrumentId(Integer acTeacherInstrumentId) {
        this.acTeacherInstrumentId = acTeacherInstrumentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_teacher_instrument.ac_teacher_instrument_teacherId
     *
     * @return the value of ac_teacher_instrument.ac_teacher_instrument_teacherId
     *
     * @mbggenerated
     */
    public Integer getAcTeacherInstrumentTeacherid() {
        return acTeacherInstrumentTeacherid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_teacher_instrument.ac_teacher_instrument_teacherId
     *
     * @param acTeacherInstrumentTeacherid the value for ac_teacher_instrument.ac_teacher_instrument_teacherId
     *
     * @mbggenerated
     */
    public void setAcTeacherInstrumentTeacherid(Integer acTeacherInstrumentTeacherid) {
        this.acTeacherInstrumentTeacherid = acTeacherInstrumentTeacherid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_teacher_instrument.ac_teacher_instrument_instrumentId
     *
     * @return the value of ac_teacher_instrument.ac_teacher_instrument_instrumentId
     *
     * @mbggenerated
     */
    public Integer getAcTeacherInstrumentInstrumentid() {
        return acTeacherInstrumentInstrumentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_teacher_instrument.ac_teacher_instrument_instrumentId
     *
     * @param acTeacherInstrumentInstrumentid the value for ac_teacher_instrument.ac_teacher_instrument_instrumentId
     *
     * @mbggenerated
     */
    public void setAcTeacherInstrumentInstrumentid(Integer acTeacherInstrumentInstrumentid) {
        this.acTeacherInstrumentInstrumentid = acTeacherInstrumentInstrumentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_teacher_instrument
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ac_teacher_instrument other = (ac_teacher_instrument) that;
        return (this.getAcTeacherInstrumentId() == null ? other.getAcTeacherInstrumentId() == null : this.getAcTeacherInstrumentId().equals(other.getAcTeacherInstrumentId()))
            && (this.getAcTeacherInstrumentTeacherid() == null ? other.getAcTeacherInstrumentTeacherid() == null : this.getAcTeacherInstrumentTeacherid().equals(other.getAcTeacherInstrumentTeacherid()))
            && (this.getAcTeacherInstrumentInstrumentid() == null ? other.getAcTeacherInstrumentInstrumentid() == null : this.getAcTeacherInstrumentInstrumentid().equals(other.getAcTeacherInstrumentInstrumentid()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_teacher_instrument
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getAcTeacherInstrumentId() == null) ? 0 : getAcTeacherInstrumentId().hashCode());
        result = prime * result + ((getAcTeacherInstrumentTeacherid() == null) ? 0 : getAcTeacherInstrumentTeacherid().hashCode());
        result = prime * result + ((getAcTeacherInstrumentInstrumentid() == null) ? 0 : getAcTeacherInstrumentInstrumentid().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_teacher_instrument
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", acTeacherInstrumentId=").append(acTeacherInstrumentId);
        sb.append(", acTeacherInstrumentTeacherid=").append(acTeacherInstrumentTeacherid);
        sb.append(", acTeacherInstrumentInstrumentid=").append(acTeacherInstrumentInstrumentid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}