package com.artclub.model;

import java.io.Serializable;

public class ac_user implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_user.ac_user_id
     *
     * @mbggenerated
     */
    private Integer acUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_user.ac_user_useraccount
     *
     * @mbggenerated
     */
    private String acUserUseraccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_user.ac_user_username
     *
     * @mbggenerated
     */
    private String acUserUsername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_user.ac_user_password
     *
     * @mbggenerated
     */
    private String acUserPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_user.ac_user_role
     *
     * @mbggenerated
     */
    private Integer acUserRole;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_user.ac_user_realname
     *
     * @mbggenerated
     */
    private String acUserRealname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_user.ac_user_realId
     *
     * @mbggenerated
     */
    private String acUserRealid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_user.ac_user_status
     *
     * @mbggenerated
     */
    private Integer acUserStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_user.ac_user_email
     *
     * @mbggenerated
     */
    private String acUserEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_user.ac_user_addtime
     *
     * @mbggenerated
     */
    private String acUserAddtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_user.ac_user_lastIP
     *
     * @mbggenerated
     */
    private String acUserLastip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_user.ac_user_lastLoinTime
     *
     * @mbggenerated
     */
    private String acUserLastlointime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_user.ac_user_headImg
     *
     * @mbggenerated
     */
    private String acUserHeadimg;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ac_user
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_user.ac_user_id
     *
     * @return the value of ac_user.ac_user_id
     *
     * @mbggenerated
     */
    public Integer getAcUserId() {
        return acUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_user.ac_user_id
     *
     * @param acUserId the value for ac_user.ac_user_id
     *
     * @mbggenerated
     */
    public void setAcUserId(Integer acUserId) {
        this.acUserId = acUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_user.ac_user_useraccount
     *
     * @return the value of ac_user.ac_user_useraccount
     *
     * @mbggenerated
     */
    public String getAcUserUseraccount() {
        return acUserUseraccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_user.ac_user_useraccount
     *
     * @param acUserUseraccount the value for ac_user.ac_user_useraccount
     *
     * @mbggenerated
     */
    public void setAcUserUseraccount(String acUserUseraccount) {
        this.acUserUseraccount = acUserUseraccount == null ? null : acUserUseraccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_user.ac_user_username
     *
     * @return the value of ac_user.ac_user_username
     *
     * @mbggenerated
     */
    public String getAcUserUsername() {
        return acUserUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_user.ac_user_username
     *
     * @param acUserUsername the value for ac_user.ac_user_username
     *
     * @mbggenerated
     */
    public void setAcUserUsername(String acUserUsername) {
        this.acUserUsername = acUserUsername == null ? null : acUserUsername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_user.ac_user_password
     *
     * @return the value of ac_user.ac_user_password
     *
     * @mbggenerated
     */
    public String getAcUserPassword() {
        return acUserPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_user.ac_user_password
     *
     * @param acUserPassword the value for ac_user.ac_user_password
     *
     * @mbggenerated
     */
    public void setAcUserPassword(String acUserPassword) {
        this.acUserPassword = acUserPassword == null ? null : acUserPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_user.ac_user_role
     *
     * @return the value of ac_user.ac_user_role
     *
     * @mbggenerated
     */
    public Integer getAcUserRole() {
        return acUserRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_user.ac_user_role
     *
     * @param acUserRole the value for ac_user.ac_user_role
     *
     * @mbggenerated
     */
    public void setAcUserRole(Integer acUserRole) {
        this.acUserRole = acUserRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_user.ac_user_realname
     *
     * @return the value of ac_user.ac_user_realname
     *
     * @mbggenerated
     */
    public String getAcUserRealname() {
        return acUserRealname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_user.ac_user_realname
     *
     * @param acUserRealname the value for ac_user.ac_user_realname
     *
     * @mbggenerated
     */
    public void setAcUserRealname(String acUserRealname) {
        this.acUserRealname = acUserRealname == null ? null : acUserRealname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_user.ac_user_realId
     *
     * @return the value of ac_user.ac_user_realId
     *
     * @mbggenerated
     */
    public String getAcUserRealid() {
        return acUserRealid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_user.ac_user_realId
     *
     * @param acUserRealid the value for ac_user.ac_user_realId
     *
     * @mbggenerated
     */
    public void setAcUserRealid(String acUserRealid) {
        this.acUserRealid = acUserRealid == null ? null : acUserRealid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_user.ac_user_status
     *
     * @return the value of ac_user.ac_user_status
     *
     * @mbggenerated
     */
    public Integer getAcUserStatus() {
        return acUserStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_user.ac_user_status
     *
     * @param acUserStatus the value for ac_user.ac_user_status
     *
     * @mbggenerated
     */
    public void setAcUserStatus(Integer acUserStatus) {
        this.acUserStatus = acUserStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_user.ac_user_email
     *
     * @return the value of ac_user.ac_user_email
     *
     * @mbggenerated
     */
    public String getAcUserEmail() {
        return acUserEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_user.ac_user_email
     *
     * @param acUserEmail the value for ac_user.ac_user_email
     *
     * @mbggenerated
     */
    public void setAcUserEmail(String acUserEmail) {
        this.acUserEmail = acUserEmail == null ? null : acUserEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_user.ac_user_addtime
     *
     * @return the value of ac_user.ac_user_addtime
     *
     * @mbggenerated
     */
    public String getAcUserAddtime() {
        return acUserAddtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_user.ac_user_addtime
     *
     * @param acUserAddtime the value for ac_user.ac_user_addtime
     *
     * @mbggenerated
     */
    public void setAcUserAddtime(String acUserAddtime) {
        this.acUserAddtime = acUserAddtime == null ? null : acUserAddtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_user.ac_user_lastIP
     *
     * @return the value of ac_user.ac_user_lastIP
     *
     * @mbggenerated
     */
    public String getAcUserLastip() {
        return acUserLastip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_user.ac_user_lastIP
     *
     * @param acUserLastip the value for ac_user.ac_user_lastIP
     *
     * @mbggenerated
     */
    public void setAcUserLastip(String acUserLastip) {
        this.acUserLastip = acUserLastip == null ? null : acUserLastip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_user.ac_user_lastLoinTime
     *
     * @return the value of ac_user.ac_user_lastLoinTime
     *
     * @mbggenerated
     */
    public String getAcUserLastlointime() {
        return acUserLastlointime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_user.ac_user_lastLoinTime
     *
     * @param acUserLastlointime the value for ac_user.ac_user_lastLoinTime
     *
     * @mbggenerated
     */
    public void setAcUserLastlointime(String acUserLastlointime) {
        this.acUserLastlointime = acUserLastlointime == null ? null : acUserLastlointime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_user.ac_user_headImg
     *
     * @return the value of ac_user.ac_user_headImg
     *
     * @mbggenerated
     */
    public String getAcUserHeadimg() {
        return acUserHeadimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_user.ac_user_headImg
     *
     * @param acUserHeadimg the value for ac_user.ac_user_headImg
     *
     * @mbggenerated
     */
    public void setAcUserHeadimg(String acUserHeadimg) {
        this.acUserHeadimg = acUserHeadimg == null ? null : acUserHeadimg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_user
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ac_user other = (ac_user) that;
        return (this.getAcUserId() == null ? other.getAcUserId() == null : this.getAcUserId().equals(other.getAcUserId()))
            && (this.getAcUserUseraccount() == null ? other.getAcUserUseraccount() == null : this.getAcUserUseraccount().equals(other.getAcUserUseraccount()))
            && (this.getAcUserUsername() == null ? other.getAcUserUsername() == null : this.getAcUserUsername().equals(other.getAcUserUsername()))
            && (this.getAcUserPassword() == null ? other.getAcUserPassword() == null : this.getAcUserPassword().equals(other.getAcUserPassword()))
            && (this.getAcUserRole() == null ? other.getAcUserRole() == null : this.getAcUserRole().equals(other.getAcUserRole()))
            && (this.getAcUserRealname() == null ? other.getAcUserRealname() == null : this.getAcUserRealname().equals(other.getAcUserRealname()))
            && (this.getAcUserRealid() == null ? other.getAcUserRealid() == null : this.getAcUserRealid().equals(other.getAcUserRealid()))
            && (this.getAcUserStatus() == null ? other.getAcUserStatus() == null : this.getAcUserStatus().equals(other.getAcUserStatus()))
            && (this.getAcUserEmail() == null ? other.getAcUserEmail() == null : this.getAcUserEmail().equals(other.getAcUserEmail()))
            && (this.getAcUserAddtime() == null ? other.getAcUserAddtime() == null : this.getAcUserAddtime().equals(other.getAcUserAddtime()))
            && (this.getAcUserLastip() == null ? other.getAcUserLastip() == null : this.getAcUserLastip().equals(other.getAcUserLastip()))
            && (this.getAcUserLastlointime() == null ? other.getAcUserLastlointime() == null : this.getAcUserLastlointime().equals(other.getAcUserLastlointime()))
            && (this.getAcUserHeadimg() == null ? other.getAcUserHeadimg() == null : this.getAcUserHeadimg().equals(other.getAcUserHeadimg()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_user
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getAcUserId() == null) ? 0 : getAcUserId().hashCode());
        result = prime * result + ((getAcUserUseraccount() == null) ? 0 : getAcUserUseraccount().hashCode());
        result = prime * result + ((getAcUserUsername() == null) ? 0 : getAcUserUsername().hashCode());
        result = prime * result + ((getAcUserPassword() == null) ? 0 : getAcUserPassword().hashCode());
        result = prime * result + ((getAcUserRole() == null) ? 0 : getAcUserRole().hashCode());
        result = prime * result + ((getAcUserRealname() == null) ? 0 : getAcUserRealname().hashCode());
        result = prime * result + ((getAcUserRealid() == null) ? 0 : getAcUserRealid().hashCode());
        result = prime * result + ((getAcUserStatus() == null) ? 0 : getAcUserStatus().hashCode());
        result = prime * result + ((getAcUserEmail() == null) ? 0 : getAcUserEmail().hashCode());
        result = prime * result + ((getAcUserAddtime() == null) ? 0 : getAcUserAddtime().hashCode());
        result = prime * result + ((getAcUserLastip() == null) ? 0 : getAcUserLastip().hashCode());
        result = prime * result + ((getAcUserLastlointime() == null) ? 0 : getAcUserLastlointime().hashCode());
        result = prime * result + ((getAcUserHeadimg() == null) ? 0 : getAcUserHeadimg().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_user
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", acUserId=").append(acUserId);
        sb.append(", acUserUseraccount=").append(acUserUseraccount);
        sb.append(", acUserUsername=").append(acUserUsername);
        sb.append(", acUserPassword=").append(acUserPassword);
        sb.append(", acUserRole=").append(acUserRole);
        sb.append(", acUserRealname=").append(acUserRealname);
        sb.append(", acUserRealid=").append(acUserRealid);
        sb.append(", acUserStatus=").append(acUserStatus);
        sb.append(", acUserEmail=").append(acUserEmail);
        sb.append(", acUserAddtime=").append(acUserAddtime);
        sb.append(", acUserLastip=").append(acUserLastip);
        sb.append(", acUserLastlointime=").append(acUserLastlointime);
        sb.append(", acUserHeadimg=").append(acUserHeadimg);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}