package com.artclub.model;

import java.io.Serializable;

public class ac_videocourse implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_videocourse.ac_videoCourse_id
     *
     * @mbggenerated
     */
    private Integer acVideocourseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_videocourse.ac_videoCourse_url
     *
     * @mbggenerated
     */
    private String acVideocourseUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_videocourse.ac_videoCourse_instrumentId
     *
     * @mbggenerated
     */
    private Integer acVideocourseInstrumentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_videocourse.ac_videoCourse_time
     *
     * @mbggenerated
     */
    private String acVideocourseTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_videocourse.ac_videoCourse_status
     *
     * @mbggenerated
     */
    private Integer acVideocourseStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ac_videocourse
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_videocourse.ac_videoCourse_id
     *
     * @return the value of ac_videocourse.ac_videoCourse_id
     *
     * @mbggenerated
     */
    public Integer getAcVideocourseId() {
        return acVideocourseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_videocourse.ac_videoCourse_id
     *
     * @param acVideocourseId the value for ac_videocourse.ac_videoCourse_id
     *
     * @mbggenerated
     */
    public void setAcVideocourseId(Integer acVideocourseId) {
        this.acVideocourseId = acVideocourseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_videocourse.ac_videoCourse_url
     *
     * @return the value of ac_videocourse.ac_videoCourse_url
     *
     * @mbggenerated
     */
    public String getAcVideocourseUrl() {
        return acVideocourseUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_videocourse.ac_videoCourse_url
     *
     * @param acVideocourseUrl the value for ac_videocourse.ac_videoCourse_url
     *
     * @mbggenerated
     */
    public void setAcVideocourseUrl(String acVideocourseUrl) {
        this.acVideocourseUrl = acVideocourseUrl == null ? null : acVideocourseUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_videocourse.ac_videoCourse_instrumentId
     *
     * @return the value of ac_videocourse.ac_videoCourse_instrumentId
     *
     * @mbggenerated
     */
    public Integer getAcVideocourseInstrumentid() {
        return acVideocourseInstrumentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_videocourse.ac_videoCourse_instrumentId
     *
     * @param acVideocourseInstrumentid the value for ac_videocourse.ac_videoCourse_instrumentId
     *
     * @mbggenerated
     */
    public void setAcVideocourseInstrumentid(Integer acVideocourseInstrumentid) {
        this.acVideocourseInstrumentid = acVideocourseInstrumentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_videocourse.ac_videoCourse_time
     *
     * @return the value of ac_videocourse.ac_videoCourse_time
     *
     * @mbggenerated
     */
    public String getAcVideocourseTime() {
        return acVideocourseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_videocourse.ac_videoCourse_time
     *
     * @param acVideocourseTime the value for ac_videocourse.ac_videoCourse_time
     *
     * @mbggenerated
     */
    public void setAcVideocourseTime(String acVideocourseTime) {
        this.acVideocourseTime = acVideocourseTime == null ? null : acVideocourseTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_videocourse.ac_videoCourse_status
     *
     * @return the value of ac_videocourse.ac_videoCourse_status
     *
     * @mbggenerated
     */
    public Integer getAcVideocourseStatus() {
        return acVideocourseStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_videocourse.ac_videoCourse_status
     *
     * @param acVideocourseStatus the value for ac_videocourse.ac_videoCourse_status
     *
     * @mbggenerated
     */
    public void setAcVideocourseStatus(Integer acVideocourseStatus) {
        this.acVideocourseStatus = acVideocourseStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_videocourse
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ac_videocourse other = (ac_videocourse) that;
        return (this.getAcVideocourseId() == null ? other.getAcVideocourseId() == null : this.getAcVideocourseId().equals(other.getAcVideocourseId()))
            && (this.getAcVideocourseUrl() == null ? other.getAcVideocourseUrl() == null : this.getAcVideocourseUrl().equals(other.getAcVideocourseUrl()))
            && (this.getAcVideocourseInstrumentid() == null ? other.getAcVideocourseInstrumentid() == null : this.getAcVideocourseInstrumentid().equals(other.getAcVideocourseInstrumentid()))
            && (this.getAcVideocourseTime() == null ? other.getAcVideocourseTime() == null : this.getAcVideocourseTime().equals(other.getAcVideocourseTime()))
            && (this.getAcVideocourseStatus() == null ? other.getAcVideocourseStatus() == null : this.getAcVideocourseStatus().equals(other.getAcVideocourseStatus()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_videocourse
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getAcVideocourseId() == null) ? 0 : getAcVideocourseId().hashCode());
        result = prime * result + ((getAcVideocourseUrl() == null) ? 0 : getAcVideocourseUrl().hashCode());
        result = prime * result + ((getAcVideocourseInstrumentid() == null) ? 0 : getAcVideocourseInstrumentid().hashCode());
        result = prime * result + ((getAcVideocourseTime() == null) ? 0 : getAcVideocourseTime().hashCode());
        result = prime * result + ((getAcVideocourseStatus() == null) ? 0 : getAcVideocourseStatus().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_videocourse
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", acVideocourseId=").append(acVideocourseId);
        sb.append(", acVideocourseUrl=").append(acVideocourseUrl);
        sb.append(", acVideocourseInstrumentid=").append(acVideocourseInstrumentid);
        sb.append(", acVideocourseTime=").append(acVideocourseTime);
        sb.append(", acVideocourseStatus=").append(acVideocourseStatus);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}