package com.artclub.model;

import java.io.Serializable;

public class ac_video_assess implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_video_assess.ac_video_assess_id
     *
     * @mbggenerated
     */
    private Integer acVideoAssessId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_video_assess.ac_video_assess_videoId
     *
     * @mbggenerated
     */
    private Integer acVideoAssessVideoid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_video_assess.ac_video_assess_userId
     *
     * @mbggenerated
     */
    private Integer acVideoAssessUserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_video_assess.ac_video_assess_assess
     *
     * @mbggenerated
     */
    private Integer acVideoAssessAssess;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_video_assess.ac_video_assess_videoTable
     *
     * @mbggenerated
     */
    private String acVideoAssessVideotable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ac_video_assess
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_video_assess.ac_video_assess_id
     *
     * @return the value of ac_video_assess.ac_video_assess_id
     *
     * @mbggenerated
     */
    public Integer getAcVideoAssessId() {
        return acVideoAssessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_video_assess.ac_video_assess_id
     *
     * @param acVideoAssessId the value for ac_video_assess.ac_video_assess_id
     *
     * @mbggenerated
     */
    public void setAcVideoAssessId(Integer acVideoAssessId) {
        this.acVideoAssessId = acVideoAssessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_video_assess.ac_video_assess_videoId
     *
     * @return the value of ac_video_assess.ac_video_assess_videoId
     *
     * @mbggenerated
     */
    public Integer getAcVideoAssessVideoid() {
        return acVideoAssessVideoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_video_assess.ac_video_assess_videoId
     *
     * @param acVideoAssessVideoid the value for ac_video_assess.ac_video_assess_videoId
     *
     * @mbggenerated
     */
    public void setAcVideoAssessVideoid(Integer acVideoAssessVideoid) {
        this.acVideoAssessVideoid = acVideoAssessVideoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_video_assess.ac_video_assess_userId
     *
     * @return the value of ac_video_assess.ac_video_assess_userId
     *
     * @mbggenerated
     */
    public Integer getAcVideoAssessUserid() {
        return acVideoAssessUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_video_assess.ac_video_assess_userId
     *
     * @param acVideoAssessUserid the value for ac_video_assess.ac_video_assess_userId
     *
     * @mbggenerated
     */
    public void setAcVideoAssessUserid(Integer acVideoAssessUserid) {
        this.acVideoAssessUserid = acVideoAssessUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_video_assess.ac_video_assess_assess
     *
     * @return the value of ac_video_assess.ac_video_assess_assess
     *
     * @mbggenerated
     */
    public Integer getAcVideoAssessAssess() {
        return acVideoAssessAssess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_video_assess.ac_video_assess_assess
     *
     * @param acVideoAssessAssess the value for ac_video_assess.ac_video_assess_assess
     *
     * @mbggenerated
     */
    public void setAcVideoAssessAssess(Integer acVideoAssessAssess) {
        this.acVideoAssessAssess = acVideoAssessAssess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_video_assess.ac_video_assess_videoTable
     *
     * @return the value of ac_video_assess.ac_video_assess_videoTable
     *
     * @mbggenerated
     */
    public String getAcVideoAssessVideotable() {
        return acVideoAssessVideotable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_video_assess.ac_video_assess_videoTable
     *
     * @param acVideoAssessVideotable the value for ac_video_assess.ac_video_assess_videoTable
     *
     * @mbggenerated
     */
    public void setAcVideoAssessVideotable(String acVideoAssessVideotable) {
        this.acVideoAssessVideotable = acVideoAssessVideotable == null ? null : acVideoAssessVideotable.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_video_assess
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ac_video_assess other = (ac_video_assess) that;
        return (this.getAcVideoAssessId() == null ? other.getAcVideoAssessId() == null : this.getAcVideoAssessId().equals(other.getAcVideoAssessId()))
            && (this.getAcVideoAssessVideoid() == null ? other.getAcVideoAssessVideoid() == null : this.getAcVideoAssessVideoid().equals(other.getAcVideoAssessVideoid()))
            && (this.getAcVideoAssessUserid() == null ? other.getAcVideoAssessUserid() == null : this.getAcVideoAssessUserid().equals(other.getAcVideoAssessUserid()))
            && (this.getAcVideoAssessAssess() == null ? other.getAcVideoAssessAssess() == null : this.getAcVideoAssessAssess().equals(other.getAcVideoAssessAssess()))
            && (this.getAcVideoAssessVideotable() == null ? other.getAcVideoAssessVideotable() == null : this.getAcVideoAssessVideotable().equals(other.getAcVideoAssessVideotable()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_video_assess
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getAcVideoAssessId() == null) ? 0 : getAcVideoAssessId().hashCode());
        result = prime * result + ((getAcVideoAssessVideoid() == null) ? 0 : getAcVideoAssessVideoid().hashCode());
        result = prime * result + ((getAcVideoAssessUserid() == null) ? 0 : getAcVideoAssessUserid().hashCode());
        result = prime * result + ((getAcVideoAssessAssess() == null) ? 0 : getAcVideoAssessAssess().hashCode());
        result = prime * result + ((getAcVideoAssessVideotable() == null) ? 0 : getAcVideoAssessVideotable().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_video_assess
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", acVideoAssessId=").append(acVideoAssessId);
        sb.append(", acVideoAssessVideoid=").append(acVideoAssessVideoid);
        sb.append(", acVideoAssessUserid=").append(acVideoAssessUserid);
        sb.append(", acVideoAssessAssess=").append(acVideoAssessAssess);
        sb.append(", acVideoAssessVideotable=").append(acVideoAssessVideotable);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}